### ISSUE TITLE
When installed with Composer, activation of Polylang fails to missing autoload.php

### ISSUE THREAD

**Issue by sjaks** [polylang/polylang#1003]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Include polylang in composer.json (I used versions 3.1.2 and 3.1.4).
2. Run `composer install`.
3. Observe that the site is broken.

```
Warning: require(/data/wordpress/htdocs/wp-content/plugins/polylang/vendor/autoload.php): failed to open stream: No such file or directory in /data/wordpress/htdocs/wp-content/plugins/polylang/polylang.php on line 70
```

Polylang is installed to the correct location but `vendor` directory is not created there. Polylang tries, however, to access the `autoload.php` file from there.

## Expected behavior and actual behavior

Polylang should have `vendor/` created when it's installed. When installing Polylang from WP Admin, it can be activated.

```
$ composer show wpsyntex/polylang
name     : wpsyntex/polylang
descrip. : Making WordPress multilingual.
keywords : 
versions : * 3.1.4
type     : wordpress-plugin
license  : GNU General Public License v3.0 or later (GPL-3.0-or-later) (OSI approved) https://spdx.org/licenses/GPL-3.0-or-later.html#licenseText
homepage : https://polylang.pro
source   : [git] https://github.com/polylang/polylang.git ef9fc783fa386debed895f92c6cf515865df3148
dist     : [zip] https://api.github.com/repos/polylang/polylang/zipball/ef9fc783fa386debed895f92c6cf515865df3148 ef9fc783fa386debed895f92c6cf515865df3148
path     : /data/wordpress/htdocs/wp-content/plugins/polylang
names    : wpsyntex/polylang
```

**Comment by chesio** [comment]
By reading https://github.com/polylang/polylang#how-to-set-up-polylang I guess you have to run `composer build` from Polylang directory to have "internal" autoloader generated.

**Comment by manooweb** [comment]
Thanks @chesio, it's exact 👍

To complete:
- this repository isn't a ready to use composer package. It's our repository where we develop Polylang core.
- a build process is now useful to make Polylang ready to work before activating it. Because our own autoloader was replaced with the composer one since our 2.8.x releases but also the javascript and css files really used by Polylang aren't provided anymore in this repository, only the sources are.
- `composer build` command is sufficient because it includes both the `composer install` command and `npm` commands to build javascript and css files as expected by Polylang to be activated and work correctly.
- at the opposite the Polylang plugin you can find on the official [WordPress.org](https://wordpress.org/plugins/polylang/) directory is a ready to use built version you can install indeed from the WordPress admin plugins management page. The whole required [composer](https://plugins.trac.wordpress.org/browser/polylang/trunk/vendor/composer), [javascript](https://plugins.trac.wordpress.org/browser/polylang/trunk/js/build) and [css](https://plugins.trac.wordpress.org/browser/polylang/trunk/css/build) files are there. It's the place we recommend to install Polylang especially for users who [haven't any development knowledge](https://github.com/polylang/polylang#-polylang)

**Comment by chesio** [comment]
> Include polylang in composer.json (I used versions 3.1.2 and 3.1.4).

Btw. if you want to use Polylang (or any other plugin hosted in WordPress Plugins Directory) in Composer-based install, then I recommend using [WordPress Packagist](https://wpackagist.org/).

**Comment by dguruwu** [comment]
Great information here guys, I just started toying around with Polylang and recently discovered Composer in my attempts to liberate myself from being a point-click WP junkie.  Thank you all for your continued development and support of Polylang!
