### ISSUE TITLE
Making it stable - testing

### ISSUE THREAD

**Issue by szepeviktor** [polylang/polylang#105]
Please consider adding at least unit tests.
I'll send a PR to run them in TravisCI.

**Comment by Chouby** [comment]
There are phpunit tests. I would not call them unit tests but rather integration tests. They are not public at the moment, because they were initially separate from Polylang.  They are also wuite messy and I have to arrange them before making them publicly available here.

Some of these tests are testing need 3rd party plugins or specifically need Twenty Fourteen or Twenty Seventeen (so not necessary the default them of the current WordPress version). Is it possible to run them with TravisCI?

**Comment by szepeviktor** [comment]
> Is it possible to run them with TravisCI?

Yes. I'll be possibly writing the test scripts.

**Comment by szepeviktor** [comment]
This is how: http://wp-cli.org/commands/scaffold/plugin-tests/

**Comment by Chouby** [comment]
OK. Let me some time to arrange things (a bit) and I will include them in this repo.

**Comment by Chouby** [comment]
I have created a new branch phpunit https://github.com/polylang/polylang/tree/phpunit to work on this topic.

Some tests need plugins (Yoast SEO, JetPack and WordPress Importer) or themes (Twenty Fourteen, Twenty Seventeen). I put them in separate subdirectories. (NB there is a test fro YARPP but the plugin is not needed).

Themes are usually included in WordPress directory, but the current latest version does not include Twenty Fourteen anymore. I added it on my local test suite at its usual place. I made that when WP 4.7 was released to go faster but it's not mantainable in the long term when changing the WordPress version. I put plugins aside the wordpress directory instead of the usual plugins directory.    

So my current local test suite directory structure looks lik this:

|-jetpack
|-wordpress
  |-wp-content
    |-themes
      |-twentyfourteen
      |-twentyseventeen
|-wordpress-importer
|-wordpress-seo
|-wordpress-tests-lib

I don't know if it's good for TracisCI. If you can help to setup these tests on TravisCI, that would be very nice.

**Comment by szepeviktor** [comment]
Thank you!

Could you try running WP-CLI? `wp scaffold plugin-tests` http://wp-cli.org/commands/scaffold/plugin-tests/
It will generate the testing environment with Travis config.

I hope it is easy to adapt.

**Comment by Chouby** [comment]
In 0c1577380f8fa33ea754ca03d04a7ff05ca0fb1f
Travis-CI is now setup to run phpunit tests.
* I did not went down to PHP 5.2 due to errors (most probably in tests as, until now, I took care to PHP 5.2 in Polylang but not in tests). 
* My attempts to run integration tests with Yoast SEO, WordPress Importer and Jetpack were not conclusive. Not sure why. I may try again later, but will stop here for now and will go on running them locally.
