### ISSUE TITLE
Enhancement: No cookie by default. Only create cookie when language is changed (not before!) - to be compliant with EU cookie law

### ISSUE THREAD

**Issue by 54mu3l** [polylang/polylang#1104]
## Prerequisites

- [X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Open any wordpress website with polylang active
2. Have a look at the cookies: polylang cookie is set

## Expected behavior and actual behavior

When I follow those steps, I see that the cookie has been created, even if I (the user) hasn't explicitly changed the language (yet).

I was expecting the cookie to be set only after I (the user) explicitly changed the language.

## Why this enhancement is important

This feature is required to be compliant with "Opinion 04/2012 on Cookie Consent Exemption".

On your website (https://polylang.pro/doc/is-polylang-compatible-with-the-eu-cookie-law/) you wrongly state:

> According to the section 3.6 of the  [Opinion 04/2012 on Cookie Consent Exemption](http://ec.europa.eu/justice/data-protection/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf), this cookie is part of the user interface customization and may be considered as requested by the user.

But the "Opinion 04/2012 on Cookie Consent Exemption" (https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf) clearly states:
> They are only set if the user has explicitly requested the service to remember a certain piece of information, for example, by clicking on a button or ticking a box.

**"Has explicitly requested"** is the keyword here.

## Why it matters to us

We're a privacy centered website and we don't need to consent our users for cookies (as of today). But we would like to use polylang and since polylang sets the cookie immediately, we would be required to consent the users. This leaves us with two options:
a) don't use polylang
b) add a cookie banner and ask for consent

Option b isn't a option for us, therefore we would be greatful if you could add this feature and make polylang set the cookie only after the user **explicitly** changed the language.

Thank you.

**Comment by chesio** [comment]
Hi @54mu3l,

just a side note - there is a third option as well:

```php
/**
 * Disable Polylang cookie, set the site language from URL only.
 * https://polylang.pro/doc/php-constants/
 */
define('PLL_COOKIE', false);
```

That works well if a website has a clear URL structure (= every URL has language part).

**Comment by 54mu3l** [comment]
Hi @chesio,

yes, I saw this in the doc (https://polylang.pro/doc/php-constants/) but because it says:
> Be aware that in this case, not everything will work correctly.

I wasn't sure what "not everything" was referencing to. But thank you for the clarification.

**Comment by chesio** [comment]
Perhaps "not everything" covers URLs without language part, like `wp-json` end-point. Unfortunately we don't use it that much in our projects, so I can't really tell. But we have no issues with regular front-end queries.

**Comment by Chouby** [comment]
The purpose of the doc https://polylang.pro/doc/is-polylang-compatible-with-the-eu-cookie-law/ is to provide the link to EU document (which is itself an opinion, not the law), not to provide a legal advice.

I don't know how to write "this cookie is part of the user interface customization and may be considered as requested by the user" in a better way so that's not misinterpreted. Hopefully the next sentence clarify it "Please check if this cookie requires an explicit user consent in your own country", as, at the time I wrote it, the law was not the same in all countries.

However, the things about the language cookie are a bit more complex than what this document may let think.

In Polylang, the cookie has 3 functions:
1. Remember the language of the last page you browsed. This clearly enters in the user preference filed described in the EU doc. However, if you kept the Polylang defualt options, the feature is not used and the cookie not used for this feature as well.
2. Select the language of pages not using rewrite rules: `wp-login.php`, `wp-signup.php`. The feature was present long before WordPress added the language selector on the login screen. And it has still an advantage on it, it's automatic. Thanks to the cookie. Whether it's functionnal or user preference may be subject to interpretation. If your site doesn't allow user registration, the feature, and thus the cookie, may not be useful.
3. Provide an automatic way to select the correct language for ajax requests. This is the trickiest feature. If your theme or plugins use ajax requests on front, these requests may require language filtering (for example an ajax products search). If the request includes a `lang` parameter, Polylang will use it. But this requires that the theme or plugin has been adapted to Polylang. On the other hand, if no `lang` parameter is detected, the language cookie is used. This makes things automatically without developers caing about multilingual compatibility. For me, this usage of the cookie is functionnal and not a user preference (but again it's not a legal advice, but my own interpretation). We can't know if a site uses ajax requests on front or not.

And some feature that was added last year:
```php
add_filter( `pll_cookie_expiration`, `__return_zero` );
```
allo to use a session cookie.

Hope these clarifications help.
