### ISSUE TITLE
wpml-config.xml not translating the options

### ISSUE THREAD

**Issue by d762** [polylang/polylang#1115]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Download Waiting Plugin (only normal free countdown plugin for non-comercial websites at the moment)
2. Add shortcode to the loading-page.php wherever you would like or via widgets.
3. create wpml-config.xml and add following code: `<wpml-config>
    <admin-texts>
        <key name="pbc_unit_terms" />
			<key name="years" />
			<key name="months" />
			<key name="days" />
			<key name="hours" />
			<key name="minutes" />
			<key name="seconds" />
    </admin-texts>
</wpml-config>`
4. hit save in the strings translations, translate the strings and hit save again.

## Expected behavior and actual behavior

The strings stay the same as before: untranslated.

The strings should get translated.

**Comment by Chouby** [comment]
This happens because the plugin gets its option as soon as it is loaded., thus preventing any plugin to filter (in our case "translate") the option. You can report the issue to the author and explain that it's bad practice for a plugin to do anything before the action `plugins_loaded` is fired. If the option is loaded adter the action `plugins_loaded` is fired, then Polylang will be able to translate it.

**Comment by d762** [comment]
Thanks, solved it myself.
