### ISSUE TITLE
Routing breaks when provding URL query parameter `lang` while using path prefix

### ISSUE THREAD

**Issue by AndreasMaros** [polylang/polylang#1117]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently (see actual behaviour below)

## Steps to reproduce the issue

1. Set PolyLang's URL modifications to path prefix (option 3 as per [the docs](https://polylang.pro/doc/url-modifications/#language-is-set-from-the-code-in-URL)
2. Call a post/page with an additional URL query parameter `lang`, providing an existing translation different from the current language: http://example.com/en/path/to/page?lang=fr 

## Expected behavior and actual behavior

When I follow those steps, I see a 404 error in some cases, a redirection to the page's translation in other cases (i.e. to the translation indicated by the `lang` parameter). In some especially weird cases (when using a custom theme an providing a _non-existent_ language slug) the otherwise unused `index.php` is being rendered (which is not meant to happen ever).

I was expecting PolyLang to completely ignore URL parameters when set to using a path prefix, or at least for the path prefix to overrule any query parameter.

Somehow URLs to actual pages containing the language slug as a path prefix **and** an additional language slug parameter turned up in our search index and yield unexpected results. I'm fairly certain I could just strip the `lang` parameter entirely through nginx settings ro WP filters, but the fact that PolyLang somehow processes the query string even though configured not to use smells like a bug. The redirection that occurs sometimes could at least be justified, but I'd say a 404 is unacceptable.

Is there an option I'm missing, or some filter?

**Comment by Chouby** [comment]
I don't reproduce the issue at least not for posts and pages for which I test because these are cases where I expect the language parameter to be ignored. However, I can imagine that it could lead to a 404 if you provide incorrect informations such as 2 different languages.

The language is a taxonomy where terms are mutually exclusive, and often, we let WordPress work as with any other taxonomy without interfering. However, if you do something like (which could be how WordPress interprets your url):
```php
$args = array(
	'tax_query' => array(
		'relation' => 'AND',
		array(
			'taxonomy' => 'language',
			'field'    => 'slug',
			'terms'    => array( 'en' ),
		),
		array(
			'taxonomy' => 'language',
			'field'    => 'slug',
			'terms'    => array( 'fr' ),
		),
	)
);		
$query = new WP_Query( $args );
```
then this is expected to give no result.

Anyway, this seems to be a case specif to your install. So the best thing you have to do is to remove the wrong language information in your url.
