### ISSUE TITLE
Author Bio Not Translating

### ISSUE THREAD

**Issue by aaronrobb** [polylang/polylang#1135]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Add author biography in each language in the author editor page
2. Load a post that was created in multiple languages
3. View the page in each language

## Expected behavior and actual behavior

Expected behaviour: Author biography shows in each language
Actual behaviour: Only the biography from the default language shows

More details:
The page is built in Twig/Timber, and uses ```{{ author.description }}``` as the code to show the description.

**Comment by Chouby** [comment]
We don't have any experience with Twig/Timber. I just re-tested with TWenty Twenty One and did not find anything wrong. So it looks like your issue is specific to Timber or your setup.

To achieve the expected result, we don't do anything fancy, simply filter [`get_user_metadata`](https://github.com/polylang/polylang/blob/3.2.7/frontend/frontend-filters.php#L169-L182). 

Hopefully, knowing where we act will help you to find out the source of your issue. Here are some things you could check.
- Is the class corretly loaded (Polylang loaded in frontend context)? 
- Is the filter correctly added?
- Is the filter correcly applied? 
- Is the current language correctly set?
