### ISSUE TITLE
pll_after_languages_cache not firing

### ISSUE THREAD

**Issue by seebeen** [polylang/polylang#123]
Filter **pll_after_languages_cache** is never being fired because it either fetches language list from local cache, or from transient.

I have a plugin that extends serbian language into multiple scripts, and there is no simple way for me to extend your language switcher without overriding complete output.

Filter not firing issue can be solved by moving:

`$languages = apply_filters( 'pll_after_languages_cache', $languages );`
`$this->cache->set( 'languages', $languages );`

From lines 118,119 to line 121, above

`$args = wp_parse_args( $args, array( 'hide_empty' => false ) );`

**Comment by Chouby** [comment]
The filter is applied (it is used internally by Polylang). It is intentionally at this position to make sure that it is applied only once. After that the languages list is indeed cached.

You must make sure to add your filter as soon as possible in your plugin because it is applied when the action 'plugins_loaded' is fired with priority 1.

**Comment by seebeen** [comment]
I cannot load my plugin with priority 1, it needs to be at least 20, so when I load my plugin the hook won't fire.

Moving the after_cache filter below does not make a performance difference.

**Comment by Chouby** [comment]
Then you can do something like:
```
$languages = PLL()->model->get_languages_list();
// do what you want
PLL()->model->cache->set( 'languages', $languages );
```
