### ISSUE TITLE
Filter pll_languages_list not apply from theme. Not working any option to order languages

### ISSUE THREAD

**Issue by Triloworld** [polylang/polylang#1251]
## Prerequisites
Try `
 add_filter( 'pll_languages_list', function($languages){return rsort($languages); }, 1, 1);
`

- [X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X] This bug happens with only Polylang plugin active
- [X] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install WP with 2 languages
2. Add switch theme 
3. Now try using settings for ordering languages
4. I try to add ` add_filter( 'pll_languages_list', function($languages){return rsort($languages); }, 1, 1);` to sort in different way. 
5. Delete transient with additional plugin or by `delete_transient( 'pll_languages_list' );` in `after_setup_theme`

## Expected behavior and actual behavior
Order change to different one have some hook available to use. None in documentation and not working simple settings
Order stay like adding filter or changing order isn't working ;/

Newest version of plugin

**Comment by Triloworld** [comment]
This place filter to use as custom languages order: https://github.com/polylang/polylang/blob/0c4b5aa03d51f57ee97f7b319c1dfa06217bc74c/include/model.php#L125-L200

**Comment by Chouby** [comment]
The WordPress load sequence is as follows:
- Load mu-plugins
- Load plugins
- Define the locale and load WordPress translations
- Load the theme.
As you see the theme comes too late. That's why the filter is inefficient in a theme and can only be used in a plugin or mu-plugin as stated in the doc. You mist even use it before the action `plugins_loaded` is fired.
That said,
- Ordering languages [can be done easily in the interface](https://polylang.pro/doc/configure-the-languages/#order). I it doesn't work, that's most probably  due to a conflict with a 3rd party code.
- The filter `pll_languages_list` [will be deprecated in the next version 3.4](https://github.com/polylang/polylang/blob/060c9d9a7de939f5a84ef576bfd5d53c6c146e6e/include/model.php#L944).
