### ISSUE TITLE
Polylang version 3 has a bug and it is incompatible with Advance Custom Field (ACF)

### ISSUE THREAD

**Issue by materialsmoke** [polylang/polylang#1279]
Polylang version 2 is working well with Advance Custom Field (ACF)

I want to update my website and use the latest version of Polylang which is version 3.3.3

in this situation I can see a bug in Polylang:

1- I create an article and add an image in ACF

2- save the article

3- translate the article to another language

and here is the result: it doesn't show the media in translated articles.

and after I click on the plus button to translate it to another language, as you can see there is no image.

but in Polylang version 2, I have the image after I translate it.

here is a video about the bug:

https://www.mediafire.com/file/c8sac0rp3bmujca/polylang_3_bug.mp4/file

I know if in the polylang settings, in languages -> settings -> media -> Media Automatically duplicate media in all languages when uploading a new file. if I check this option it will duplicate the image, when I upload and will work... but I don't want to have duplicated images.

I want only one image when I upload an image. (like polylang version 2).

@Chouby could you please add `bug` label to this issue?

**Comment by Chouby** [comment]
It seems that you are a Polylang Pro customer. Please contact our helpdesk for support.

**Comment by Chrystll** [comment]
I understand now, you are exploiting a bug that we fixed in the 2.8 version https://github.com/polylang/polylang/blob/master/changelog.txt#L298.

To summarize, if these English images are not translated in Danish (linked by translation by the pen icon) thus these English images are displayed in your Dansk page when using the 2.7.4 version (or an older) because of the bug. The bug was that you could display a content (here your English images) in a page, post in a different language (here your Dansk page). 

What you can do is to activate the duplicate content icon at the post level in the Polylang Pro metabox, this your image will be duplicated on the fly in your Dansk language.

I check on my side and I didn't receive your ticket. If you need further help please make sure to contact us by our form just here https://polylang.pro/support/

**Comment by materialsmoke** [comment]
@Chrystll 
I just sent a support ticket please confirm you have received my ticket

#### I want one image in all translated articles... is it possible?

I know if in the polylang settings, in languages -> settings -> media -> Media Automatically duplicate media in all languages when uploading a new file. if I check this option it will duplicate the image, when I upload and will work... but I don't want to have duplicated images.

please explain more what should I do?

here is the question on stackoverflow. even I add a bounty on it, no body have answered the question. and I got 3 point from asking the question. so this is not only my problem. it's other people's problem too:
https://stackoverflow.com/questions/76260906/polylang-version-3-has-a-bug-and-it-is-incompatible-with-advance-custom-field-a
