### ISSUE TITLE
Toggle outputting country code in hreflang

### ISSUE THREAD

**Issue by karelvuong** [polylang/polylang#128]
In `frontend-filters-links.php`, line 218 has a ternary that only outputs the country code in hreflang if there are multiple locales being used:

```$lang = $count[ $languages[ $locale ] ] > 1 ? $locale : $languages[ $locale ]; // Output the country code only when necessary```

Is there a toggle that allows us to override this to always show it?

Thanks in advance!

**Comment by Chouby** [comment]
From SEO perspective, it is generally better to target all English speaking people (for example) rather than only targetting only English speaking people in US. That said, you have full control of the output with the filter `pll_rel_hreflang_attributes`. See https://github.com/polylang/polylang/blob/2.1.3/frontend/frontend-filters-links.php#L235
