### ISSUE TITLE
Double quotes causes issue with MySQL 8

### ISSUE THREAD

**Issue by ejstrup-checkmate** [polylang/polylang#1290]
https://github.com/polylang/polylang/blob/106901c5a63c0c67742795b8112467b9ff45d8e1/include/model.php#L864

The double quotes in the returned SQL statement causes an "uknown column 'language' in order caluse" error, which results in polylang not working altogether.

**Comment by Chouby** [comment]
According to the doc, double quotes are supported: https://dev.mysql.com/doc/refman/8.0/en/string-literals.html
As our tests usually don't run with this version, I specifcally ran tests with MySQL 8.0.33. Everything is green: https://app.travis-ci.com/github/polylang/polylang/builds/263462016 (FYI, 577 tests go through this line in the current version 3.4.2).
So your issue is probably coming from elsewhere and most probably a conflict with another plugin.
Could you provide the complete SQL query in your error message?

**Comment by ejstrup-checkmate** [comment]
Ah, I should have added that it's happening with ANSI_QUOTES enabled.

**Comment by Chouby** [comment]
We can fix that, but it's strange that you run a WP install with this mode enabled as it is officially incompatible: https://github.com/WordPress/WordPress/blob/6.2.2/wp-includes/class-wpdb.php#L654 (I know you can filter this list).
