### ISSUE TITLE
Posts are duplicating content to other languages

### ISSUE THREAD

**Issue by andreb07** [polylang/polylang#1304]
## Prerequisites

- [ X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ X] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create a new specific custom post
2. Fill out some ACF field
3. Save
4. Create a translations from this post

## Expected behavior and actual behavior

When I follow those steps, I see...

Everytime I change any field and save the post, every field from other languages changes 2. Like the posts are duplicating the content.

I was expecting...

When I change a field in one language, it shouldn't change the other languages..

--------

This doesn't happen in every custom post, and started happening when I changed servers!
This is a default behaviour and I can't find any solution for this and why this is happenning!
Only happen with ACF fields!

Please help!

**Comment by eCoreSolutions** [comment]
I am experiencing the same problem on Version 3.4.3 and I verified that everything is unchecked in Settings/Synchronization. I found a related issue at https://wordpress.org/support/topic/acf-flexible-content-are-being-synchronized-even-if-it-shouldnt/ from 4 months ago experiencing the same issue after version of Polylang 3.3.1

**Comment by Chrystll** [comment]
@andreb07 Indeed, if you check this option with Polylang thus your acf custom fields are synchronized. This is the expected behavior.

@eCoreSolutions The topic that you point is related to Polylang Pro, not to Polylang. With Polylang Pro the synchronization of the acf custom field are not handled by the "custom field" option the Synchronization module, we use another way to handle them. If you are using Polylang Pro, please contact our [helpdesk dedicated to our customers](https://polylang.pro/support/), don't forget to provide your license key.
