### ISSUE TITLE
PLL_Model::get_languages_list() was called incorrectly

### ISSUE THREAD

**Issue by jignesh-travelopia** [polylang/polylang#1343]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Update Polylang Pro plugin to latest version 3.4.5
2. activate plugin in PHPUnit bootstrap file
3. run PHPUnit test

## Expected behavior and actual behavior

Here is my bootstrap file to load the plugin.
```
function _manually_load_environment() {
	update_option( 'active_plugins', [ 'polylang-pro/polylang.php']);

	add_action(
		'pll_no_language_defined',
		function () {
			// To add languages we need early access of $wp_rewrite.
			$GLOBALS['wp_rewrite'] = new WP_Rewrite();
			$options   = get_option( 'polylang', [] );
			$model     = new PLL_Admin_Model( $options );
			$languages = [
				'gb' => 'UK',
			];

			foreach ( $languages as $slug => $label ) {
				$args = [
					'slug'       => $slug,
					'name'       => $label,
					'locale'     => 'en_' . strtoupper( $slug ),
					'rtl'        => false,
					'term_group' => 0,
				];

				$model->add_language( $args );
			}
			wp_cache_flush();
		}
	);

}
tests_add_filter( 'muplugins_loaded', '_manually_load_environment' );
```
Upon running the PHPUnit tests, It's throwing the doing it wrong Notice: `Notice: Function PLL_Model::get_languages_list() was called <strong>incorrectly</strong>. It must not be called before the hook 'pll_pre_init'.`

I see it has been mentioned on the change log here but not have much information about it. [https://polylang.pro/polylang-3-4-eases-the-translation-of-custom-tables/](https://polylang.pro/polylang-3-4-eases-the-translation-of-custom-tables/)

**Comment by Screenfeed** [comment]
Hello 👋 

### A short explanation about the change in `PLL_Model::get_languages_list()`

Previously we were working with a list of languages that were incomplete (some properties were populated on the fly after the language instantiations), which led us to various issues along the way, so we made this change in order to have a list of complete languages right from the start.

### About your bootstrap

#### Solution 1

This may not be the best place to create the language(s). If you take a look at [our tests](https://github.com/polylang/polylang/blob/449cbec46ce54f56989a94a24941c6b7211e3cb4/tests/phpunit/tests/test-crud-posts.php#L14-L17), you can see that we create them in the method `wpSetUpBeforeClass()`. Maybe this can solve your issue.

#### Solution 2

Otherwise, maybe I can suggest another solution by tweaking your way of doing. I think this may work:
```php
function _manually_load_environment() {
	update_option( 'active_plugins', [ 'polylang-pro/polylang.php']);

	add_action(
		'pll_pre_init',
		function () {
			if ( ! did_action( 'pll_no_language_defined' ) ) {
				return;
			}

			// To add languages we need early access of $wp_rewrite.
			// ...
```

`PLL_Model::add_language()` uses `PLL_Model::get_languages_list()` internally, so it cannot be called before `'pll_pre_init'`. So I suggest to move your hook from `'pll_no_language_defined'` to `'pll_pre_init'`, and use `did_action()` to make sure that `'pll_no_language_defined'` has been fired.

#### Solution 3

If all the above solutions failed, there is a last one by using `PLL_Model::set_languages_ready()`:

```php
		function () {
			// To add languages we need early access of $wp_rewrite.
			$GLOBALS['wp_rewrite'] = new WP_Rewrite();
			$options   = get_option( 'polylang', [] );
			$model     = new PLL_Admin_Model( $options );
			$languages = [
				'gb' => 'UK',
			];

			$model->set_languages_ready();

			foreach ( $languages as $slug => $label ) {
				// ...
```
