### ISSUE TITLE
Strings translation option

### ISSUE THREAD

**Issue by Chrystll** [polylang/polylang#14]
Hi Chouby

Could you please take a look at this topic: https://wordpress.org/support/topic/slight-annoyance-when-editing-strings-manually-saving-them-returns-to-page-1?replies=3  ?

`

/* Your own code for setting $this->_column_headers */

        $per_page = 20; /* this seems to be what you're using, or maybe it's WP's default? You could also do $per_page = $this->get_pagination_arg('per_page'); which ought to work */

        /* Let's figure out what page the user is currently
         * looking at.
         */
        $current_page = $this->get_pagenum();

        /**
         * REQUIRED for pagination.
         */
        $total_items = count($items);

        /**
         * The WP_List_Table class does not handle pagination for us, so we need
         * to ensure that the data is trimmed to only the current page. We can use
         * array_slice() to
         */
        $items = array_slice($items,(($current_page-1)*$per_page),$per_page);

        $this->items = $items;

      /**
         * REQUIRED. We also have to register our pagination options & calculations.
         */
        $this->set_pagination_args( array(
            'total_items' => $total_items,                  //WE have to calculate the total number of items
            'per_page'    => $per_page,                     //WE have to determine how many items to show on a page
            'total_pages' => ceil($total_items/$per_page)   //WE have to calculate the total number of pages
        ) );

`

**Comment by Chouby** [comment]
I confirm the bug. However, the issue is not related to how I handle pagination as suggested by the forum topic as the code in **settings/table-strings.php** (not settings/table-settings.php) is handled correctly but seems to be related with some conflicting WordPress javascript which resets the 'paged' POST value to 1 just before the form is submitted : See https://github.com/WordPress/WordPress/blob/master/wp-admin/js/common.js#L565-L572
