### ISSUE TITLE
 Undefined array key "menu" in frontend-nav-menu.php on line 280

### ISSUE THREAD

**Issue by jankod** [polylang/polylang#1456]
## Prerequisites

- [ ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- x[ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x ] This bug happens with only Polylang plugin active
- [? ] This bug happens with a default WordPress theme active
- [ x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. call 
`Timber::get_pages_menu();  `
in functions.php  (timber plugin theme)

## Expected behavior and actual behavior

When I follow those steps, I see...
`Warning: Undefined array key "menu" in /..../Wordpress/wp-content/plugins/polylang/frontend/frontend-nav-menu.php on line 280`

**Comment by Chouby** [comment]
The error occurs in a method hooked to `wp_nav_menu_args`. If you look at the [WordPress code](https://github.com/WordPress/WordPress/blob/6.4.3/wp-includes/nav-menu-template.php#L60-L97) above this filter, you can see that even if `wp_nav_menu()` is called with `menu` argument, it's filled by WordPress before the filter is applied. So if there is an error on your site, its probably due to a plugin, theme or custom code doing wrong by unsetting this argument.
