### ISSUE TITLE
Some taxonomy terms are randomly missing

### ISSUE THREAD

**Issue by sebastienserre** [polylang/polylang#1531]
Polylang : Version 3.6.4
Wordpress : Version 6.6.1

I have the same problem since I upgrade Wordpress and the plugin Polylang.
Sometime, each category disappears, but not all.

![image](https://github.com/user-attachments/assets/087a66ce-2326-411a-8bb2-8898855cac25)

I have only this categories : 
![image](https://github.com/user-attachments/assets/fef8c81b-c158-4385-8f2d-b2878aa9c7f9)

When everything works, I have more categories and child categories !

I found a fix, but any way, after few days the problem comeback !

My temporary fix : 
- Go to category
- Modify a category
- Change nothing and click on Update
- You will see all your categories appears : 

![image](https://github.com/user-attachments/assets/7104fa06-5452-4a3f-be56-2fa2460530af)

**### To Polylang team's, can you found what is the problem ?**

_Originally posted by @natharock in https://github.com/polylang/polylang/issues/323#issuecomment-2330880675_

**Comment by sebastienserre** [comment]
Hello https://github.com/natharock

By reading deeply yor issue and the original comment of https://github.com/polylang/polylang/issues/323, This is not the same issue. That's why I'm opening this new issue.

We do not reproduce your issue on our side.
To be able to work on it, w'll need ytou to explain us step by step how to reproduce this issue in a basic confirguration having:
- WordPress 6.6.1
- Polylang 3.6.4
- Twenty Twenty Four

Regards

**Comment by natharock** [comment]
Hello,

I'm looking for myself since today how to reproduce this result.
For the moment a get this result (category missing) two times, the morning without touch anything the day before, without explaination.

I just found how to fix it (thx God !). But now I try to found how to reproduce it !

**Comment by ondrejbecva** [comment]
Hello,

I would like to confirm that the problem is not only happening to natharock.

The problem happens on our website as well. After some time the categories disappear from the listing in the administration. The only way to save the linking of categories between languages is to switch the display of all languages and then save the main categories (which have nested categories as well). Then, after switching between languages, all categories show up as they should.

If the categories don't show up in the administration, their query doesn't work on the frontend either.

The odd thing is that if categories disappear from other languages, there is always one language in which the categories remain. If I open a category via this one language, the category link can be seen and the edit link of the other languages works as well. So if I go to edit via the pencil icon and save the category in the language where the category is missing, it will show up in the listing, but it will disappear from the other language where it was originally.

The problem will show up again in some time after this temporary fix.
Even though no changes are made to the site.

- WordPress 6.6.2
- Polylang 3.6.4
- Custom theme

**Comment by thomazcia** [comment]
Polylang v. 3.6.5
All plugins and WordPress updated.

I encountered the same issue with a custom taxonomy that lost its link, which I recreated.

Another issue is related to switching languages, even though all categories and taxonomies are correctly registered and linked.

When I’m on the taxonomy (slug = l) in Portuguese (main language) and click the Spanish flag to switch languages, it displays the homepage.
site.com.br/l/linha-tradicional (pt-br)
site.com.br/es/l/linea-tradicional (es)
It also goes to the homepage.

The same issue occurs with another taxonomy (slug = t).
site.com.br/t/secos (pt-br)
site.com.br/es/t/seco (es)
It also goes to the homepage.

However, if I’m on the Spanish page - site.com.br/es/t/seco - and click the Brazilian flag, I’m redirected to the correct page - site.com.br/t/secos.
This occurs with both taxonomies.

When debugging by analyzing the "pt-br" page linked to "es," it shows correctly, so what I’ve identified is that the function displaying languages is where the error is. This applies to the widget function, menu, or directly in PHP—any of the functions below exhibit the same error.


pll_the_languages();

 pll_the_languages( array( 'show_flags' => 1, 'show_names' => 0 ) ); 
 
 pll_the_languages( array( 'dropdown' => 1 ) );


As shown in the image below, I am on the taxonomy page in Portuguese, and through debugging, it identified the correct Spanish version, but the link in the menu (flags) does not recognize it.

![Screenshot_1](https://github.com/user-attachments/assets/487a1e22-1d62-4b51-8c45-f1ecc20812b8)
