### ISSUE TITLE
Enable translations for all custom post types

### ISSUE THREAD

**Issue by martinhahn** [polylang/polylang#164]
It seems like polylang only supports translations for public custom post types. Since we often use custom post types that are not public available but referenced within another post or page, polylang translations are not available for those posts.

**How we use non-public custom post types**
We use them for better structure and to reduce content management efforts. For example we use custom post types to add salespersons. But they do not have a single page each. Their credentials are only shown in a content box within a page. Therefore the custom post type is not public which results in the loss of translation-capability.

**Comment by grappler** [comment]
@martinhahn See the documentation. https://polylang.pro/doc/multilingual-custom-post-types-and-taxonomies/

You can define support for certain post types in the code with the filters `pll_get_post_types` and 
´pll_get_taxonomies`.

This was previously discussed in #11

**Comment by Chouby** [comment]
Yes. Private custom post types are hidden by default to avoid any misuse. There is also the [wpml-config.xml file](https://polylang.pro/doc/the-wpml-config-xml-file/) which makes it possible to translate any post type and taxonomy.

**Comment by b4dnewz** [comment]
hi @Chouby is possible to activate a custom post type (or taxonomy) instead of just show/hide from the settings page ?
I need to enable a custom post type by default and right now I've to do it manually from the settings page.

I'm looking into the [settings-cpt](https://github.com/polylang/polylang/blob/73f3eb7b8e5d8f6e8eec2bd5b51ace77b45a414d/settings/settings-cpt.php) code but seems not possible (there are no filters in the update function), can you suggest me a prefered way to ensure that a (public) custom post type has the translations enabled by default?

Many thanks in advance.

**Comment by Chouby** [comment]
That's what I proposed above. Use a wpml-config.xml file. Oryou can use the filter `pll_copy_post_metas` instead.

**Comment by amouratoglou** [comment]
```
add_filter('pll_get_post_types', 'unset_cpt_pll', 10, 2);
function unset_cpt_pll( $post_types, $is_settings ) {

    $post_types['postype'] = 'postype';

    return $post_types;
}
```
