### ISSUE TITLE
Conflict with Caldera Forms entry viewer API request

### ISSUE THREAD

**Issue by Shelob9** [polylang/polylang#172]
I am the developer of Caldera Forms and would like to find a good fix for a conflict with our plugin found by one of our mutual users.

I'd be happy to put in a pull request to make your plugin work with ours better. I'm worried this bug could effect other parts of our plugin that use that endpoint.

## Prerequisites

- [X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [X] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. When using the site in a translated mode, go to Caldera Forms entry viewer, click "Edit Link"
2. In network inspector note that the API request goes to `/en/cf-api`, not `/cf-api`
3.Request 404s.

Then I also tried filtering our API url to remove `/en` - https://pastebin.com/V0kecSsx this caused the API request to go to the right URL, but that 301ed to the translated URL.

We need to prevent that 301 when the request is to Caldera API (cf-api). I think the filter pll_check_canonical_url is best for this, by looking at your code real quick, but not sure.

**Comment by florent-cdl** [comment]
I get this bug on my multi-language website.

A workaround (thanks to Josh) is to add the filter below : 
add_filter( 'pll_check_canonical_url', '__return_false' );

But perhaps this one has consequences... Maybe it could be more precise and target only /cf-api/ url ?

Thanks.
Florent

**Comment by Shelob9** [comment]
My concern about using `add_filter( 'pll_check_canonical_url', '__return_false' );` is that I worry that will prevent the translation from ever working.

Your specific concern was with the API request for the entry edit modal. So maybe only return false, if the GET vars for that kind of request are set.

```
	add_filter( 'pll_check_canonical_url', function( $url ){
		if( isset( $_GET[ 'modal' ]) && 'view_entry' === $_GET[ 'modal' ]){
			return false;
		}
		
		return $url;
	});
```

**Comment by Chouby** [comment]
Josh, could you explain how this link is generated? This would help me to find which Polylang filter conflicts.

**Comment by Shelob9** [comment]
@Chouby The link is generated using `Caldera_Forms::get_submit_url()` See - https://github.com/CalderaWP/Caldera-Forms/blob/master/classes/core.php#L3483

Originally  @florent-cdl was getting a 404 error. But then they usd the filter in that function to remove `/en`. That triggered the 301

**Comment by Chouby** [comment]
Thanks. According to my tests, the conflict is not in `Caldera_Forms::get_submit_url()`, although the way the link is created can confuse 3rd party plugins using the [home_url filter](https://github.com/WordPress/WordPress/blob/4.8.1/wp-includes/link-template.php#L3025) as the `$path` argument of the filter is empty.

The conflict is in fact in `check_canonical_url` as you suggest. I don't know why but it seems that the query always returns the latest page created. As the language code is not found in the requested url, Polylang adds it. As this function aims to extend the functionnality of the WP function [redirect_canonical ](https://github.com/WordPress/WordPress/blob/master/wp-includes/canonical.php#L42), did you make anything special to stop `redirect_canonical` to redirect to the latest created page?

Otherwise returning false to the filter `pll_check_canonical_url` and targeting the modal as you suggest should work fine. Returning false in all cases would indeed break the canonical redirection mechanism of Polylang, meaning that mysite.com/my-post-in-english and mysite.com/en/my-post-in-english would both be accepted creating duplicate content issues.

**Comment by Chouby** [comment]
Closing as Caldera Forms will be discontinued: https://calderaforms.com/2021/03/the-future-of-caldera-forms/
