### ISSUE TITLE
Switch timezone with language

### ISSUE THREAD

**Issue by szepeviktor** [polylang/polylang#184]
Hello @Chouby !

Are there plans to set timezone based on language? It is the `gmt_offset` core option.

In the meanwhile could you suggest a work-around with a hook?

**Comment by Chouby** [comment]
Hello Viktor,

I don't plan to add this. The timezone is more related to locations rather than languages. It should be however easy to add to the strings translations with a wpml-config.xml file:
```
<wpml-config>
	<admin-texts>
   		<key name="gmt_offset" />
	</admin-texts>
</wpml-config>
```
Take care not to keep UTC+0 in the WordPress option as empty values are not added to the strings translations table.

**Comment by szepeviktor** [comment]
Thank you @Chouby 
Is there a non-wpml-compatibility way to translate `gmt_offset`?

**Comment by szepeviktor** [comment]
I usually keep every "extra" options turned off because of speed.

**Comment by Chouby** [comment]
Yes. You can use `pll_register_string()` on admin to register the string in the table. The on frontend, you can filter the option with `pll__()`.

**Comment by szepeviktor** [comment]
Thank you.
