### ISSUE TITLE
String translations for non-admins

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#20]
Is it possible to allow other roles to access String translations only? Maybe a custom permission?

**Comment by Chouby** [comment]
I am using the 'manage_options' capability because the strings translations are intended to translate options. Thus I believe that only users having this capability should have access to it.

**Comment by JoryHogeveen** [comment]
Ah ok, I am also using them for front-end stuff like strings in a theme and widgets. My clients all have the editor role so they can't get to settings they could break but I'd like to allow them to translate these strings.
If you have any idea on how to accomplish this without the need of extra plugins or .mo files, please let me know.

**Comment by Chouby** [comment]
Theme options and widgets should not be accessible to editors. Am I wrong?

**Comment by JoryHogeveen** [comment]
You are correct but I change these and added the "edit_theme_options" cap to the editor role.
Thus I know this is not a default configuration :)

I'll close this issue because I guess it is out of the scope for your support but if you have an idea for a workaround, please let me know (maybe a filter for the capability??)

**Comment by diggy** [comment]
>strings translations are intended to translate options

I think a lot of people (you know, those who don't read the docs) "abuse" the strings translations for translating strings in theme template files. Maybe the strings translations tab could benefit from a subtle warning with regard to this?

**Comment by Chouby** [comment]
@JoryHogeveen Changing the capability level is already possible:
`
add_action( 'init', function() {
	if ( PLL_ADMIN ) {
		remove_action( 'admin_menu', array( PLL(), 'add_menus' ) );
		add_action( 'admin_menu', function() {
			add_submenu_page( 'options-general.php', $title = __( 'Languages', 'polylang' ), $title, 'edit_theme_options', 'mlang', array( PLL(), 'languages_page' ) );
		} );
	}
} );`
But it impacts all the tabs, not only the 'strings translations', so that may not be what you want. Having a separate capability would probably require a structure change. Maybe, I would need to create a specific menu instead of using a submenu of settings.

@diggy If you are referring to https://wordpress.org/plugins/polylang-theme-strings/, it does not disturb me as we can consider that translating the theme requires the 'manage_options' capability. What's more disturbing is using this to translate content as NextGen Gallery does.

**Comment by JoryHogeveen** [comment]
@Chouby Yes I thought of that solution but this indeed allows users to see all settings, not just the translations.
If I can find some time I will look into this. It's not a high priority issue, more a thought to enhance this functionality :)

**Comment by Chouby** [comment]
I reopen this issue for the future.

**Comment by Hito01** [comment]
Hi,
What do you think about adding custom capabilities for Polylang ? It would be great to have a real control of what users can/cannot do with the plugin.

**Comment by JoryHogeveen** [comment]
I'm all +1 for that!

**Comment by diggy** [comment]
FYI, I came across another theme strings translation addon: https://github.com/marcinkazmierski/Polylang---theme-translation

**Comment by Chouby** [comment]
To clarify what I did in https://github.com/polylang/polylang/commit/2de3193b5df1c326e30e3cfcf3d7519f080d0a9b:
I moved the Languages submenu on top. Former tabs are now submenus and thus have their own capability. I kept this capability as 'manage_options' for all submenus, including the strings translations.

So to allow non-administrators to edit translations, you normally just need to add your own menu with your own capability after you tested that the current user does not have the  'manage_options' capability. For example:

```
add_action( 'admin_menu', function() {
	if ( ! current_user_can( 'manage_options' ) ) {
		add_menu_page( __( 'Strings translations', 'polylang' ), __( 'Languages', 'polylang' ), 'edit_theme_options', 'mlang_strings', null , 'dashicons-translation' );
	}
} );
```

**Comment by JoryHogeveen** [comment]
See PR, I thing this is a easier way for dev's to do this. If you change anything in your code every dev will need to adjust this aswell. This way they don't need to.

**Comment by Hito01** [comment]
@Chouby Hi, sorry but I'm not sure to understand how the change should work. I've added your action in my `functions.php`, it displays the item in the menu but when clicking on it I can't see the strings translation page. Should I do something else ? Thanks !

**Comment by Sprachprofi** [comment]
Same here, this functionality will be priceless for my site!!

**Comment by Chouby** [comment]
@Hito01 Yes you are right. I forgot the most important in this example! The link to the code to display the page :/

Here it is fixed:

```php
add_action( 'admin_menu', function() {
	if ( ! current_user_can( 'manage_options' ) && function_exists( 'PLL' ) ) {
		add_menu_page( __( 'Strings translations', 'polylang' ), __( 'Languages', 'polylang' ), 'edit_theme_options', 'mlang_strings', array( PLL() 'languages_page' , 'dashicons-translation' );
	}
} );
```
In this example I give access to the strings translations to users having the 'edit_theme_options' capability. This has no effect with standard roles. So you need to choose the capability depending on how you customized the roles.

**Comment by swissspidy** [comment]
@Chouby Have you thought about introducing separate capabilities for Polylang features like this? This allows for more fine-grained capability checks and one could assign these capabilities only to specific users. Happy to open an issue for this.

**Comment by Chouby** [comment]
My intention is to go far beyond this. In the long term, I plan to create some capabilities for translators. That would mean that you could restrict edition of any content in a language to specific users. Of course I want the strings translations to be part of this feature. But as it would interact with a lot of existing capabilities, I need time to think to the best way to do this. That's why I did not change anything to the current capability to edit strings translations. I don't want to create something now that I could break in a future version because I would have made things too quickly without enough reflection.

**Comment by jvcdk** [comment]
I have been wanting this functionality as well for my site. The reason is that I use the Maps Marker Pro plugin and they use the string translation feature to translate their map markers. Hence, in order for (contributers) to translate their maps, they need access to string translations.

So... I made the attached patch – I hope that you will consider including it in the code so that I do not have to patch my installation with each update :-D

Anyway... to describe it briefly:

In `PLL_AdminBase::add_menus`, I changed the data structure of `$tabs` from
```php
$tabs = [
  key => title,
  ...
];
```

to
```php
$tabs = [
  key => [
    'title' => title,
    'capability' => required capability,
  ],
  ...
];
```

hence that later when the filter `pll_settings_tabs` is run, WP developers are able to change required capabilities of the different sections.

I tested it out on my site with the following code

```php
add_filter('pll_settings_tabs', function($tabs) {
    if(isset($tabs['strings']['capability']))
        $tabs['strings']['capability'] = 'pll_str_translations';
    return $tabs;
});
```

where `pll_str_translations` is a custom capability I added to my site with the help of the [Members](https://wordpress.org/plugins/members/) plugin.

It works nicely – a bit to my surprise, because I had expected that I needed to modify a save function as well. From this experience, it seems to me there is a **security bug**:

Whether or not a (logged in) user can change a translation or not, does not depend on his/her capabilities. The current code (both v. 2.3.11 and my patch) only prevents the user from seeing the UI to change translations, but if he/she knew the URL to craft, he/she could probably change translations without the capability.

I may be wrong and may be missing something.

Anyway... I hope this will help somebody and that @Chouby will accept my patch :-)

BR
Jørn

[custom_caps.patch.txt](https://github.com/polylang/polylang/files/2447314/custom_caps.patch.txt)

**Comment by Chouby** [comment]
Security is a serious thing. Unless you want to potentially harm 400,000+ sites (including yours), there is no point to publicly disclose plugins vulnerabilities. If you believe that you found a vulnerability in Polylang, you can report it by contacting us at https://polylang.pro/support/.

Even if you don’t know how to contact a plugin author, you can follow
this guideline: https://developer.wordpress.org/plugins/wordpress-org/plugin-security/reporting-plugin-security-issues/ where you’ll find a way to report the vulnerability to the WordPress plugins team. The team has the email of all plugins authors.

There is no need to patch Polylang to modify the capability. I already explained how to proceed in a previous comment https://github.com/polylang/polylang/issues/20#issuecomment-269211385

**Comment by jvcdk** [comment]
Thank you directing my attention again to your example code; I believe I tried it out before but could not get it to work. It did work this time, however, so I must have done something wrong. Sorry.

Regarding security; I deleted my comment (sounded like you thought that was the best idea) and posted a support request on your page. If you would like to receive security hints that way in the future, you might want to change your wording on your form. E.g. 

"The technical support is available only to users having a valid license key. For our free products, please use the support forum on wordpress.org. " 

does not encourage non-pro users to contact you this way. Also, if a user (like I just did) went ahead and used the "Other" category in your form, you require your visitors to check the box "This is not a technical support request" – though it kind of is (a technical support request). Or at least a heads up.
