### ISSUE TITLE
Diable change wp-admin locale based on pll_language cookie

### ISSUE THREAD

**Issue by raptor235** [polylang/polylang#201]
I've been trying to use all sorts of hooks to disable the wp-admin from being change to another language and I can't seem to do it.

I tracked down the issue to PLL_Frontend_filters init function 

add_filter( 'locale', array( $this, 'get_locale' ) );

is causing the admin login page to be changed to another language based on the cookie value...

I need to disable the wp-admin backend from being changed to another language including the login screen...

what's the best way to do this? seems like support around this is very limited.

**Comment by Chouby** [comment]
Since WP 4.7, Polylang does not interfer anymore in the admin language which is chosen in the user profile as it is now a WordPress feature. 

It's true however that Polylang sets the language on the login page. The displayed language is based on the cookie value, which itself is set from the language of the last browsed page. I want to keep this as is. If you don't like it, you can use the filter `pll_preferred_language` to define the language you want. Note that this filter is not specific to the login page but applied in other cases (first visit, ajax requests).

**Comment by chesio** [comment]
> Since WP 4.7, Polylang does not interfer anymore in the admin language which is chosen in the user profile as it is now a WordPress feature. It's true however that Polylang sets the language on the login page.

I noticed that admin bar language is changed to whatever current language is when you browse site frontend as logged user - I guess there's no easy way around it?

**Comment by Chouby** [comment]
This was the initial goal of https://core.trac.wordpress.org/ticket/26511, but at some point the ticket was restricted to the locale switching function.

I would try something like this:

```php
add_action( 'admin_bar_menu', function() {
	switch_to_locale( 'fr_FR' );
}, -1 );

add_action( 'admin_bar_menu', function() {
	restore_previous_locale();
}, 9999 );
```

**Comment by chesio** [comment]
Thanks for the hint, I'll give it a try!

**Comment by raptor235** [comment]
Hey @Chouby 

I tried 

```
function my_language_fallback( $slug ) {
	return 'en';
}
```

and

```
function my_language_fallback( $slug ) {
	return 'en_US';
}
```

But it has had no affect... any other ideas to restrict the login page to only show English?

**Comment by Chouby** [comment]
If there is a cookie, the filter is not applied. I did not plan such use case. This is a bit a hack, but you could force the cookie value on the login page.
