### ISSUE TITLE
PolyLang breaks Wordpress HTTP to HTTPS redirect?

### ISSUE THREAD

**Issue by ripieces** [polylang/polylang#206]
## Prerequisites

- [X] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [X] This bug happens with only Polylang plugin active
- [X] This bug happens with a default WordPress theme active
- [X] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Set Wordpress to use https://www.domain.tld in General settings
2. Open http://www.domain.tld with Browser Cache deactivated (i.e. "deactivate Cache" in Development tools -> Network Analysis of FireFox), in order to make sure you see the current beahviour.

## Expected behavior and actual behavior

Actual: The page get's served with 200 OK through http://www.domain.tld

I was expecting: A redirect to https://www.domain.tld - as it is when PolyLang is off.

**Comment by Chouby** [comment]
I don't reproduce the issue. You may not doing the redirect the correct way. You can use a plugin like Really Simple SSL which does this correctly.

**Comment by hscanlan** [comment]
I have this exact issue. Server is IIS. My redirects are correct.

**Comment by talphatier** [comment]
Same problem here too. Has anyone news on this topic?

**Comment by HardLink** [comment]
also encountered this problem. did someone solve this problem?

**Comment by MarkTierney1975** [comment]
Same problem. Cannot find a fix. Are the Polylang settings in the database hashed?

**Comment by dtugend** [comment]
To be honest while this bug is weird and could hunt at another problem, I recommend to not relay on WordPress HTTPS redirect anyways, for example when other pages that are not front page are accessed from HTTP, they are most of the time not redirected to HTTPS, even with out PolyLang.
Thus I'd suggest to use one of these:
A) An SSL Redirection plugin (suggested already in this thread I think)
B) htaccess entries
C) Redirection in virtual host settings.

**Comment by MarkTierney1975** [comment]
As far as I can tell there weren't any redirects in there apart from the Polylang redirect.

I managed to solve (hopefully) the issue using advice from this page https://blogs.msdn.microsoft.com/azureossds/2017/08/04/http-to-https-redirect-for-wordpress-on-azure-web-app-on-linux/

Adding this to .htaccess
RewriteCond %{HTTP:X-ARR-SSL} ^$
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

And adding this to wp-config.php
define('FORCE_SSL_ADMIN', true); 
if ( isset($_SERVER['HTTP_X_ARR_SSL']) ) 
        $_SERVER['HTTPS']='on';

**Comment by jessuppi** [comment]
Howdy folks, our plugin fixes this issue (no .htaccess required) on Apache, Nginx, etc:

https://wordpress.org/plugins/force-https-littlebizzy/

**Comment by antoniods** [comment]
Same issue + bad redirect of my 2 lang. folders, 
I solved with this code : 

````
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress

**Comment by hussamhadi** [comment]
The reason this is not working is most probably the `.htaccess` file, as others pointed. Mostly due to the way `RewriteRule`s handle their flags. The `[L]` flag means if the current rule is triggered, then no other rules are executed any more. So the order of your rules and `[L]`-flags are essential here. A pretty straightforward .htaccess file for https redirects might look like this:


```# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php  # No [L] flag here anymore, so next rule will be processed even if current one succeeds

RewriteCond %{HTTPS} !on
RewriteRule ^(.*)$ https://your.domain.here/$1 [R=301,L]

</IfModule>

# END WordPress
```

**Comment by hybridvision** [comment]
@hussamhadi is right but it's important to note that you should never directly edit the rules inside the `# BEGIN WordPress` and `# END WordPress` markers because these can be overwritten at any time by WordPress itself.

As such, you should put your custom rewrite rules in a separate block above the WordPress ones:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    # Force HTTPS
    RewriteCond %{HTTPS} off
    RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</IfModule>

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
```
