### ISSUE TITLE
 how to translate name of language switcher

### ISSUE THREAD

**Issue by dodacvan** [polylang/polylang#240]
in English we have " English  - Chinese - Japanese "
so if we change language to Chinese  the name of all language  from "English  - Chinese - Japanese" to "英文 - 中文 - 日文"

**Comment by Chouby** [comment]
Polylang provides only Native language names English - 中文 - 日本語, because people are not expect to know their language name in other languages. If you want to change that, you need build your own language switcher.

In the future, please use the support forum for questions like this. GiHub issues our the right place to report bugs, not to ask questions.
