### ISSUE TITLE
Usage with Laravel Valet and Bedrock

### ISSUE THREAD

**Issue by jasperrooduijn** [polylang/polylang#250]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active (used twentyseventeen)
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Install valet (https://laravel.com/docs/5.6/valet)
2. Clone Bedrock (https://roots.io/bedrock/)
3. Register some custom post types
4. Enter some posts in several languages
4. Try to view archives / posts in several languages

## Expected behavior and actual behavior

Languages get messed up when using custom post types. Probably because Valet uses PHP controllers to dertermine redirect logics, there is no htaccess file or whatever. Also translated theme string don't work because in my case language is always on one language no matter what language I switch to.

When deploying the same code to a server (nginx) all works fine. So this must have something to do with the Local Valet server i'm using.

**Comment by antonhedling** [comment]
Guess this might be an old question. But I ran into this myself and tried to find the reason. What I found was that in the file `frontend/choose-lang.php` on line 35, there is a check if this is an ajax call or not. I don't know what the first condition does, but the second checks if the current script filename **ISNT** index.php. Normally, when visiting the site this would not be a problem, but Laravel Valet uses server.php as the script filename instead of index.php, which then causes Polylang to think we're doing some sort of ajax call or whatever and defaults to the preferred language before the query filter can set the language based on the current post.

So this isn't a solution since modifying plugin files is a big no-no, but just as an experiment, changing the line from:
`if ( Polylang::is_ajax_on_front() || false === stripos( $_SERVER['SCRIPT_FILENAME'], 'index.php' )) {`

to:
`if ( Polylang::is_ajax_on_front() || false === stripos( $_SERVER['SCRIPT_FILENAME'], 'index.php' ) && false === stripos( $_SERVER['SCRIPT_FILENAME'], 'server.php' )) {`

makes it all work from what I can see.

Annoying issue. It isn't a massive issue since it works on our staging and production server as intended, but it still makes local development harder.

**Comment by chesio** [comment]
An alternative to `false !== stripos( $_SERVER['SCRIPT_FILENAME'], 'index.php' )` check that has been recently suggested to me that might perhaps work in this case and feels more clean: `defined('WP_USE_THEMES') && WP_USE_THEMES`.

So in this case it would be `!(defined('WP_USE_THEMES') && WP_USE_THEMES)`.

**Comment by Chouby** [comment]
I don"t know Laravel Valet but I fear that blacklisting `server.php` together with `index.php `would in fact exclude files that I want to include, for example `wp-login.php`.

Using `WP_USE_THEMES` as proposed by @chesio looks much better to me. 
@antonhedling, @jasperrooduijn would this fix your issue?

**Comment by antonhedling** [comment]
Did some testing and this method works for me.
