### ISSUE TITLE
Menu shown in default language on the backend.

### ISSUE THREAD

**Issue by grappler** [polylang/polylang#26]
We are using Shortcode on the backend to visually show the shortcode. The shortcode includes code `wp_nav_menu()` to display the menu. 

The front end shows the menu in the correct language but on the backend the menu is shown in the default language.

**Comment by Chouby** [comment]
I am not surprised. wp_nav_menu is not filtered on backend (as other functions that I believed to be frontend specific). Could you explain more on the context? Are you using a specific plugin to visualize your shortcode on the backend?

**Comment by grappler** [comment]
I was also not surprised. I am using [Shortcake](https://github.com/wp-shortcake/shortcake) to visualize the shortcode on the backend.

https://wordpress.org/plugins/shortcode-ui/
https://wptavern.com/shortcake-is-now-a-wordpress-feature-plugin

**Comment by Chouby** [comment]
I downloaded the plugin. But I did not find any call to `wp_nav_menu()`. I guess you are using it in combination with a second plugin.

**Comment by grappler** [comment]
Yes, we are running it with some custom code. This is the code you should be able to use. https://gist.github.com/grappler/067845cc9716e581be5ae930caec06d3

**Comment by Chouby** [comment]
On backend, I create fictive nav menu locations, one per language. This locations are filled with the correct menu, thanks to the filter `'theme_mod_nav_menu_locations'`.

On frontend, I don't hack the nav menu locations, but fill the location with the menu in the current language, again thanks to the filter `'theme_mod_nav_menu_locations'`.

So, the same filter is used in two different ways on backend and frontend. That's why when calling `wp_nav_menu()` on backend with the usual nav menu location, you always get the menu in the default language.

To get access to the correct location on backend, you could use:
`PLL()->nav_menu->combine_location( $location, $language );`
Here the expected language is an object, not just the language code. It could be obtained with:
`PLL()->model->get_language( pll_get_post_language( $post_id ) );`

**Comment by grappler** [comment]
Do you mean editing the shortcode to something like this:?

```php
$language = PLL()->model->get_language( pll_get_post_language( $post_id ) );
$location = PLL()->nav_menu->combine_location( $a['menuposition'], $language );
<?php wp_nav_menu( array(
	'menu_class'     => 'no-list inline-list category-tags',
	'container'      => false,
	'theme_location' => $location,
) ); ?>
```

**Comment by Chouby** [comment]
Yes. It's what I meant. If you can get `$post_id` in your function.

**Comment by grappler** [comment]
Ok, got it to work with this code.

```php
<?php
if ( is_admin() ) {
	$post_id = get_the_ID();
	$language = PLL()->model->get_language( pll_get_post_language( $post_id ) );
	$location = PLL()->nav_menu->combine_location( $a['menuposition'], $language );
} else {
	$location = $a['menuposition'];
}
wp_nav_menu( array(
	'menu_class'     => 'no-list inline-list category-tags',
	'container'      => false,
	'theme_location' => $location,
) ); ?>
```
