### ISSUE TITLE
Show page/post for all languages

### ISSUE THREAD

**Issue by strarsis** [polylang/polylang#291]
Is it possible to let Polylang always show a page/post for all language filter selections (filter?), 
as 'Show all languages' is selected for this particular page/post?

[`pll_get_post_types`](https://polylang.wordpress.com/documentation/documentation-for-developers/filter-reference/#pll_get_post_types) allows this on post type-level, but not on individual post/page level.

**Comment by Chouby** [comment]
This feature is available in Polyang Pro: https://polylang.pro/doc/synchronized-posts/

**Comment by strarsis** [comment]
And if I need this only for one particular post for a special purpose (intro page), 
is there a hook or filter in Polylang that can could be used?

**Comment by Chouby** [comment]
There is no hook for that. You can activate it with `PLL()->sync_post->copy_post(  $post_id, $lang, true );`, available only Polylang Pro. But for the intro page, I would rather use only one page rather than duplicating the page in all languages. As far as I have seen it's what you did in your plugin.
