### ISSUE TITLE
Please test for existance of the object and the array Key for this check to be usefull

### ISSUE THREAD

**Issue by JordanFAVRE** [polylang/polylang#298]
https://github.com/polylang/polylang/blob/6884ccbef9282dd60ebb83f842a07a008818835f/include/model.php#L533

**Comment by Chouby** [comment]
Could you explain what bug you want to fix?
And the steps to repduce it?
I don't see how `$this->options['force_lang']` could be not defined.

**Comment by benfavre** [comment]
Had serveral installs with multisite enabled and object caching enable, not be able to reference $this->options['force_lang'] as options was empty.
The actual code is an implementation of a check. Why not check if a value exists before asignment ?

**Comment by benfavre** [comment]
Ok, thanks for looking though this.
I would argue that it makes no difference, since if you switch a version via FTP.
This single call to an unset array key on an undefined object manages to crash a site, and there are no available options for a person to have a functional site from then on, because you can't even access the plugin page to deactivate/reactivate the plugin, for the options table to update.

**Comment by benfavre** [comment]
``` <b>Warning</b>:  Creating default object from empty value in <b>/var/www/le-comptoir-du-bitcoin/apps/app/src_admin/web/app/plugins/polylang/modules/plugins/plugins-compat.php</b> on line <b>183</b><br />
```

**Comment by benfavre** [comment]
![image](https://user-images.githubusercontent.com/664679/48553815-ed827880-e8dc-11e8-9a6d-e9823c2c6b2e.png)

**Comment by benfavre** [comment]
![image](https://user-images.githubusercontent.com/664679/48553856-0be87400-e8dd-11e8-8551-55cb00b814b2.png)
Wrong message is displayed

**Comment by Chouby** [comment]
If you want to help o fix bugs, please provide context and steps to reproduce them. Also please open on issue per bug as I am not sure that all your messages are related to the same issue.

> b>Warning</b>: Creating default object from empty value in <b>/..../plugins/polylang/modules/plugins/plugins-compat.php</b> on line <b>183</b><br />
Thanks for bringing this to my attention. It's related to the compatibility with YARPP. I just noticed that YARPP has been removed from wordpress.org. I will drop the support of this plugin soon in a future version.

**Comment by benfavre** [comment]
I don't have YARPP installed.
This is all the same issue that a simple if statement would fix.
No matter what plugin or procedure you use.
$this->options['force_lang'] is undefined.

This is a complex multisite install. I have no idea what causes the value to be undefined.
I can fix this myself by simply never using your plugin again, not renewing my pro licenses and no longer suggesting it to clients. I don't really care. Thought I'd be nice and report the issue.

**Comment by Chouby** [comment]
I don't believe that a simple `if` statement would fix anything. It would just hide the notices. Something's really wrong on your site because it looks like Polylang is not initialized. Not only `$this->options['force_lang']` but probably all options as the message about Polylang versions is most probably related to `$this->options['version']` which doesn't exist too.

So if I blindly removed this notice, I would just end to stop loading Polylang early as the plugin can't work correctly without knowing what's in its options. I am quite sure that it would not help you. 

I don't know what you mean by complex multisite install. All Polylang tests are made on a multisite and we never had such issue as yours.  

GitHub issues are nice to report bugs. By bug, I mean something that you can explain how to reproduce on any site with WordPress + a default theme + Polylang (+ optionnally some other plugin to report a conflict). That's why we have this form that we ask to fill (even if you did not) when you open an issue.

If you can't explain how to reproduce, then it's no more a bug report but a support request. And we can't efficiently provide support with GiHub issues. If you are customer of Polylang Pro, then use our helpdesk which, unlike GitHub issues, is constantly monitored by support engineers.

**Comment by Chouby** [comment]
>I delay/remove some wp init stuff.
>I use custom Options loader.
One of them is probably the cause of your issues. You are doing something which prevents Polylang to initialize correctly. That a level of customization that we cannot support.
