### ISSUE TITLE
Homepage redirects to default language, only for www url

### ISSUE THREAD

**Issue by benthek** [polylang/polylang#311]
I am very satisfied with this plugin, thanks everyone for their contribution!

At this moment, I am trying to figure something out. The website I am building has English as its default language and the Dutch homepage seems to redirect to the English one, BUT only when 'www' in in the URL. I am not sure if this is a bug, but I tried all the URL settings and nothing seems to change it.

https://dance4life.nl/ stays on https://dance4life.nl/
https://www.dance4life.nl/ goes to https://dance4life.com/
While it should just stay on the Dutch language of course.

Detect browser language is not activated. I use Really Simple SSL, but deactivating doesn't seems to make a difference.

Any ideas? :-) Thanks!

**Comment by Chouby** [comment]
In my tests, the issue occurs for mutiple deomains, only on the front page, when it is a static front page. The redirect is correctly evaluated but then prevented in this filter: https://github.com/polylang/polylang/blob/2.4/frontend/frontend-static-pages.php#L140-L142

The best ( and fastest solution ) is always to handle this kind of redirect at server level. But since WordPress also handles this kind of redirect, this is a valid bug.

**Comment by Chouby** [comment]
Related #120

**Comment by matiasperes** [comment]
This has not been fixed yet. I’m having the same issue.

**Comment by MartijnOkaia** [comment]
Any news on this? Encountering this bug as well.
