### ISSUE TITLE
Polylang redirects to wrong if used behind proxy/CDN

### ISSUE THREAD

**Issue by vladaman** [polylang/polylang#321]
When site is served via CDN polylang redirects visitor to a wrong site. For example www.site.com is the public site and source.site.com is site which CDN connects to with original content.
When serving static front page and requesting www.site.com I get redirected to http://source.site.com - this is invalid behaviour. WP_HOME and WP_SITEURL is set to "http://www.site.com"

Might be similar to #209

## Prerequisites
- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

**Comment by Chouby** [comment]
We have received a few support requests like this. In all cases, it was due to a misconfiguration of the proxy. Polylang needs to read the `$_SERVER` global variable to determine the current requested url. If the proxy configuration results in wrong values in `$_SERVER`, then Polylang cannot know the current requested url. Note that WordPress itself uses the same variables. So, a misconfiguration of the proxy also results in bugs on a fresh WordPress install. Typically the canonical redirect would not work as expected.
