### ISSUE TITLE
Language switcher: Display language code

### ISSUE THREAD

**Issue by innoforce-dev** [polylang/polylang#334]
- [x] This is not a usage question 
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.

Feature suggestion:
When using the polylang "Language switcher" in a menu it would be great to have an option "Display lanuguage code". 

Background: 
We wanted to use the language switcher in one place with short codes, in another place the full language name. Short codes had the higher priority, so we just found the workaround to rename the "Full name" property in polylang settings from "English" to "EN". 

Thanks for considering this.

**Comment by Chouby** [comment]
I am generally rather not in favor to add options. But you should already be able to do what you want with a filter:

```php
add_filter( 'pll_the_languages_args', function( $args ) {
	$args['display_names_as'] = 'slug';
	return $args;
} );
```
And a bit of CSS to get uppercase language codes.

**Comment by kram08980** [comment]
Hi,

I can't make this work in CSS. Since the Select dropdowns depend on the OS or browser -not sure-, they can't be reached with CSS. I think it could be a nice addition to use them in uppercase.

¿Maybe someone found a workaround? I am using the 'pll_the_languages()' function in two different places, one with a select and the other as a list.

Thanks!
