### ISSUE TITLE
load_plugin_textdomain() in WordPress 4.6RC + Polylang 2.0.2

### ISSUE THREAD

**Issue by theleemon** [polylang/polylang#39]
Hi!

I'm testing WordPress 4.6RC in a dev site with Polylang installed and configured. A private plugin I developed is no longer loading its .mo files in the admin (in the frontend is working correctly) from the plugin's language folder using the following code:

```
add_action( 'plugins_loaded', 'my_plugins_loaded' );
function my_plugins_loaded() {
    load_plugin_textdomain( 'my-plugin-domain', false, dirname( plugin_basename( __FILE__ ) ) .  '/languages' );
}
```

I had no issues in 4.5.3. The following tickets show that 4.6 will load languages files differently:

https://core.trac.wordpress.org/ticket/34213
https://core.trac.wordpress.org/ticket/34114
https://make.wordpress.org/core/2016/07/06/bootstrapload-updates-in-4-6/

If I disable Polylang, my private plugin loads its local .mo files in the admin as expected.

Any ideas?

**Comment by GwynethLlewelyn** [comment]
Just a quick follow-up — I saw this message and sort of panicked, because I have forgotten to test my own plugins for WP 4.6 with Polylang (my test website had Polylang unactivated for some stupid reason!). So it looked like that I was reproducing @theleemon's issue (my plugins, called from inside a widget, were _not_ showing the correct language, even though the rest of the website was perfectly multilanguage) — until I noticed that the behaviour was erratic and most likely caused by caching issues. I'm still trying to figure out exactly what the problem might be (I usually do my tests with W3TC), but I think it's _not_ related to Polylang.

**Comment by GwynethLlewelyn** [comment]
To be more precise: the .mo files seem to be correctly loaded, just as before; it's just that many requests done in a relatively short amount of time, for different languages, sometimes get the text emitted from the plugins in the wrong language (even though the rest of the site is correctly loaded). And sometimes it doesn't. That's why I'm assuming it's a caching issue, and I'm trying to see if my own plugins also cache the results (I'm lazy, I haven't updated my code in quite a while), or if it's the integration with W3TC that is causing the issue.

**Comment by theleemon** [comment]
I tried my problematic plugin in a site with just Polylang and one of the default themes, and as soon as I define one language in the Polylang settings, my plugin's strings revert to English in the backend. In the frontend, the .mo files seem to be correctly loaded. So, I'm not so sure it's a caching issue.

**Comment by theleemon** [comment]
I've tried using Polylang 1.9.3 and the same issue remains. As soon as I define a language in the Polylang settings, my private plugin's strings revert to English in the backend. So, something definitely changed in 4.6RC.

**Comment by Chouby** [comment]
@theleemon you are loading your text domain too soon. If you look at wp-settings.php, ['plugins_loaded'](https://github.com/WordPress/WordPress/blob/4.5.3/wp-settings.php#L277) is fired before the [WordPress translations are loaded](https://github.com/WordPress/WordPress/blob/4.5.3/wp-settings.php#L346).  Looking at both versions 4.5.3 and 4.6, nothing looks changed regarding this.

On backend, Polylang setups the language just before, in the 'setup_theme' hook. See https://github.com/polylang/polylang/blob/2.0.2/admin/admin-base.php#L207

Starting from WP 4.6, you can just forget loading the text domain yourself, WP will do it for you as soon as you attempts to use it.

**Comment by theleemon** [comment]
I've tried three alternatives:

1. Calling `load_plugin_textdomain` in the `setup_theme` hook (before WP l10n). My plugin's strings are not translated in the backend.
2. Calling `load_plugin_textdomain` in the `init` hook (after WP l10n). My plugin's strings are not translated in the backend.
3. Not calling `load_plugin_textdomain` at all. My plugin's strings are not translated in the backend.

Keep in mind that I have no problems with plugins using language packs stored in the WP main languages folder, just private plugins not uploaded to the WP repository that rely on local .mo files stored in the plugin's own languages folder.

**Comment by theleemon** [comment]
This is an really simple example plugin so you can see the problem yourself:

[myexhibits.zip](https://github.com/polylang/polylang/files/406284/myexhibits.zip)

**Comment by Chouby** [comment]
1. Wrong test as you may come just before Polylang if you use the same priority
2. Did you make sure that `load_plugin_textdomain` is called *before* you register your post type?
3. Sorry, I was wrong. I believe that it works only for plugins hosted on wordpress.org. So it can't for you.

Keep it simple. Move
`load_plugin_textdomain( 'myexhibits', '', dirname( plugin_basename( __FILE__ ) ) .  '/languages' );`
at the beginning of the` register_post_types` function.

**Comment by theleemon** [comment]
Moving the `load_plugin_textdomain` call at the beginning of the `register_post_types` function fixed the problem. Thanks!!! It's strange that calling `load_plugin_textdomain` in the `plugins_loaded` hook was working in 4.5, though (I just followed the Codex example here: https://codex.wordpress.org/Function_Reference/load_plugin_textdomain)

**Comment by theleemon** [comment]
Well, according to the second example in the newish Code Reference here https://developer.wordpress.org/reference/functions/load_plugin_textdomain/ calls to `load_plugin_textdomain` should be done in the `init` hook.

**Comment by Chouby** [comment]
It was indeed working in WP 4.5.

When I created Polylang, a lot of plugins were loading the text domain too soon (including popular plugins, which fixed the issue since then, such as Yoast SEO or Jetpack). I thus created a mechanism to fix this (by unloading the translations in the wrong language and reloading the correct ones). 

https://core.trac.wordpress.org/ticket/34213 broke the mechanism for plugins not having the translations in wp-content/languages. I will fix that in the next version.
