### ISSUE TITLE
BUG: pll_the_languages returns empty string in REST request

### ISSUE THREAD

**Issue by aurovrata** [polylang/polylang#416]
`pll_the_languages($args);` returns an empty string when called from a REST request.

The function in the `include/api.php` on line 26 is,

```
function pll_the_languages( $args = '' ) {
	if ( PLL() instanceof PLL_Frontend ) {
		$switcher = new PLL_Switcher();
		return $switcher->the_languages( PLL()->links, $args );
	}
	return '';
}
```
`PLL()` is an instance of `PLL_REST_Request` when the function is called from the within a REST request.  

This issue can be fixed by the following change,

```
function pll_the_languages( $args = '' ) {
	if ( PLL() instanceof PLL_Frontend || PLL() instanceof PLL_REST_Request) {
		$switcher = new PLL_Switcher();
		return $switcher->the_languages( PLL()->links, $args );
	}
	return '';
}
```

**Comment by aurovrata** [comment]
The above change causes other issues with the switcher.php file trhowing a fatal error,

> PHP Fatal error:  Uncaught Error: Call to undefined method PLL_Admin_Links::get_translation_url() in /var/www/html/m2/wp-content/plugins/polylang/include/switcher.php:73

**Comment by Chouby** [comment]
`pll_the_languages` is supposed to be a template tag to display the language switcher, so is expected to be used only in theme template on frontend not in a REST resquest. What are you trying to achieve?

**Comment by aurovrata** [comment]
> pll_the_languages is supposed to be a template tag to display the language switcher, so is expected to be used only in theme template on frontend not in a REST resquest.

works fine in v2.3, but is broken in latest version.

I have a custom REST end-point with Polylang translation links I need to pass

**Comment by Chouby** [comment]
In older versions, we did not take REST requests into account, and it happened that the default behavior of Polylang, defined before the REST API was included in WP, resulted in an instanciation of `PLL_Frontend`. With the REST API becoming more popular and especially with the introduction of teh block editor, this started to be problematic and we introduced the class `PLL_REST_Request` which is supposed to better handle REST requests than `PLL_Frontend` previously did. This explains why `pll_the_languages()` was, accidentally, accessible to REST requests and is no more, which the desired behavior.

For the completeness, I tested in v2.3.11, and I got a PHP notice: `Trying to get property of non-object in /polylang/include/switcher.php on line 61` due to the current language not defined in REST requests. And the returned string appears buggy, as it always outputs links to the home pages (with `no-translation` class which is wrong).  If you need a way to get the links to the home pages, there are better ways such as `pll_languages_list( array( 'field' => 'home_url' ) )` which will returns you an array of all the homepages links.

**Comment by aurovrata** [comment]
I appreciate the detailed answer, however, I am trying to get translation for a given translated page/post ID, namely
`
pll_the_languages( array( 'raw'=>1, 'post_id'=><id of required post/page));
`
and not just the home url,  The theme I am working with uses a reactive framework to load pages on the client side using REST api calls.  

> we introduced the class PLL_REST_Request which is supposed to better handle REST requests than PLL_Frontend previously did.

Is there an alternative way to achieve this with the new class?

If not, are you planning to re-enable this functionality in a future release?

This issue is also affecting Polylang Pro.

**Comment by Chouby** [comment]
Sorry for coming back so late. I don't believe that re-introducing `pll_the_languages()` in REST requests would be a good thing, as this would re-introduce the bug with the curent language not defined.

However, there are indeed other ways to get the informations. `pll_get_post` allows you to get the i of the translation in a given language, `pll_get_post_translations` allows you to get the ids of all translations. Then `get_permalink` allows you to obtian the link.

**Comment by aurovrata** [comment]
> this would re-introduce the bug with the curent language not defined.

indeed, I have been passing the language locale in the REST request.

> However, there are indeed other ways to get the informations. pll_get_post allows you to get the i of the translation in a given language, pll_get_post_translations allows you to get the ids of all translations. Then get_permalink allows you to obtain the link.

let me try there and will report back here.

**Comment by aurovrata** [comment]
hello, 

so I confirm that `pll_languages_list` + `pll_get_post_translations` + `get_permalink` combination works to build a translation menu for given page REST request.  However, `pll_current_language` does not work.  I am closing this thread as I believe this adequately solves the issue, but will open a new one to document the current language issue.
