### ISSUE TITLE
'Cheatin' uh?' notice when switching languages (multidomain)

### ISSUE THREAD

**Issue by JoryHogeveen** [polylang/polylang#42]
I believe this is a single-login function that does this.

action: pll_xdata_set
key: the-key

Switching languages while logged in into one language domain is currently not working (v2.0.3)

Just wondering, should this be a `get` instead of a `post`?

**Comment by Chouby** [comment]
It's working on my test site. Did you look for a conflict with the theme or another plugin?
Yes the request is a `GET`

**Comment by JoryHogeveen** [comment]
No clue why this happens either.. Maybe a failed nonce check? I know nonces are build with the current user data and this isn't available on a domain where the user isn't logged in.

**Comment by Chouby** [comment]
Here I don't use nonce in the standard way. As you mentioned it's not possible before the user logged in. So I am using some session information stored in DB. The key helps to find the information stored in DB. This information is deleted as soon as it has been used one time to avoid replay. If the information is not found in DB (either because it's a wrong key or the corresponding data has been deleted), then the 'Cheatin' uh?' notice is displayed.

Since it's working on my test site, that's why I asked if you could identify a plugin or theme conflict.

**Comment by JoryHogeveen** [comment]
Problem is still there though, couldn't find the cause yet.
When I have the time to look further and find the issue I'll reopen this.

**Comment by Chouby** [comment]
OK. I still follow closed issues so if you are able to tell me more, I will reopen.

**Comment by JoryHogeveen** [comment]
Tracked the problem down to the `get_users` function you use in `PLL_Xdata_Session_Manager::get()`.
For some reason this call does not return any users even though the data is correct (`pll_xdata_{$key}` exists in the database).
Will continue and report my findings here.

**Comment by JoryHogeveen** [comment]
Found the issue!
I protect my main user from other admins by filtering the user queries, this way my main user doesn't show in any user listing etc. But this results in a non-hit when searching for metadata for that user ID and thus the login validation will fail.

One thing you could consider is using a custom query in `PLL_Xdata_Session_Manager::get()` but since this is an issue related to my own setup that is off course your own decision :).
I've fixed it with adding an exeption for when the get variables `pll_xdata_set` and/or `pll_xdata_get` are set.

**Comment by Chouby** [comment]
Thanks for the feedback. I prefer to keep using `get_users()`. I prefer to use direct DB queries only when I don't find another way.
