### ISSUE TITLE
Polyland redirects top level domain to wp-admin

### ISSUE THREAD

**Issue by pablolarrimbe** [polylang/polylang#435]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Go to my site's top level domain xxx.com with Polylang active.

## Expected behavior and actual behavior

When I follow those steps, I see...
I get redirected to the /wp-admin site.

I was expecting...

To see the site or worst case scenario to be redirected to /en.  I saw that version 2.6.5 (pro) supposedly fixed this " * Pro: Avoid translating empty front slug (could cause a wrong redirect to /wp-admin)"

Similar report here: https://wordpress.org/support/topic/polylang-redirects/

As soon as I deactivate poylang, no redirect happens on the top level domain which is the intended behaviour.

**Comment by Chouby** [comment]
I don't reprduce on my local install. Starting from a fresh install, could you provide steps to reproduce the issue?

**Comment by puyol5** [comment]
I have exactly the same behavior as described by @pablolarrimbe.

**Comment by FKasa** [comment]
I also have experienced the same issue a few times. It did disappear as soon as I logged in so I could not test which plugin caused it (if any).

**Comment by Chouby** [comment]
Without steps to reproduce, there is no way for us to help.

**Comment by FKasa** [comment]
The issue is happening right now. I will refrain from logging in as the issue disappears than. Maybe I can prove this is related to polylang if, by accessing the files directly, I disable WP plugins one by one, disabling polylang last. If disabling all plugins besides polylang does not fix it but when polylang gets disabled last it fixes the issue, that would be a very strong indication of an issue there.
I will disable anyone logging in so that they don't make the issue disappear so that we have an opportunity to figure out where the problem is. I can stop people from accessing wp-admin for 1 whole week (until the 5th of July 2020) which should give us enough time to look into it. I am in the same timezone as France, we can setup at time to have a Zoom or Jisti meeting where I can give you all the information you need. You can contact via this Google Form:
https://forms.gle/dp68hovfSbCCjy5x8

**Comment by milk531** [comment]
save issues here.
I use AWS lightsail to host the service, and use lightsail Distribution to build CDN of the site. Two domain are assign to this site, with and without www. When I use domain with www, everything works fine. When I use domian without www, Polylang will redirect to /wp-admin.
for example, domains are example.com and www.example.com, when use example.com:
```
Request URL: https://example.com/id/     // language page for id
Request Method: GET
Status Code: 301 
Remote Address: 13.225.93.77:443
Referrer Policy: strict-origin-when-cross-origin
```
```
cache-control: no-cache, must-revalidate, max-age=0
cache-control: s-maxage=10
content-length: 0
content-type: text/html; charset=UTF-8
date: Wed, 09 Jun 2021 06:31:14 GMT
expires: Wed, 11 Jan 1984 05:00:00 GMT
location: https://example.com/wp-admin/
server: Apache
via: 1.1 3922e47363801e147476c95f0336c634.cloudfront.net (CloudFront)
x-amz-cf-id: Sj2UzRqSg5SRxWIIpvZoIyra7UT2_38baEa825FHqQprh5WtmhYTNQ==
x-amz-cf-pop: HKG60-C1
x-cache: Miss from cloudfront
x-frame-options: SAMEORIGIN
x-powered-by: PHP/7.4.13
x-redirect-by: Polylang
```
