### ISSUE TITLE
pll_current_language not working in REST request

### ISSUE THREAD

**Issue by aurovrata** [polylang/polylang#501]
the function `pll_current_language` returns an empty string in a REST request

**Comment by manooweb** [comment]
Hello @aurovrata,

Could you please be more precise ?

In fact, in our side WordPress REST API compatibility is only impleted in Polylang PRO as it is indicated in the comparison table here https://polylang.pro/downloads/polylang-pro/

If you are a Polylang Pro customer with a valid license key, please contact our support by this form https://polylang.pro/support/

Thank you

**Comment by aurovrata** [comment]
> Could you please be more precise ?

well, I think it's pretty clear, the function does not work in a REST call. 

Is there an alternative way to get the current language in a REST call?

> In fact, in our side WordPress REST API compatibility is only impleted in Polylang PRO

yes, I am aware of this, but I need to create a custom REST and I need the current language.

The free plugin allows for custom REST calls to get translations and other metadata from the Polylang setup which is enough for the work I need to do.

**Comment by manooweb** [comment]
Not exactly, because we have defined a custom REST Field `lang` which isn't processed in our free version. I confirm if you want compatibility between the WordPress REST API and Polylang you need our Pro version.

`pll_current_language` is a function for a frontend context and doesn't work in a REST API context without the compatibility I talked about.

Note that we don't provide any support for the free version. This support is done by volunteers on the WordPress forum https://wordpress.org/support/plugin/polylang/

Regards

**Comment by aurovrata** [comment]
ok fair enough, there are other ways to get the current language if you know where to look.

I just hoped you people would be little more useful.

> This support is done by volunteers on the WordPress forum https://wordpress.org/support/plugin/polylang/

I am well aware, I am such a volunteer as well as coding extensions for polylang, I promote polylang in WP meetups as well as WordCamps.

This is what an open community does, it supports each other!

**Comment by aurovrata** [comment]
and PS, my clients use Polylang PRO, as I encourage that too!
