### ISSUE TITLE
Translating YoastSEO's description and title doesn't translate it in the page.

### ISSUE THREAD

**Issue by fredy31** [polylang/polylang#505]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active (Needs Yoast SEO and a custom post type)
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Needs Polylang, Yoast SEO and a custom post type.
2. Set a description for the custom post type via Yoast SEO.
3. Translate the description via Polylang.
4. The description (in the OG:description tag) is the one set in Yoast SEO, and not it's translation set in Polylang. (So in my EN/FR site, the English description shows up also in french)

## Expected behavior and actual behavior

When I follow those steps, I see...
In both languages, the description that shows up is the one set in Yoast SEO and not the one set as the translation in polylang's string translation

I was expecting...
The translated description should be the one appearing, and have priority on the default Yoast SEO one.

**Comment by GGustavoGuerra** [comment]
Hey @fredy31!

Something similar happens to me, in my case, the homepage (with listing of posts, not static) does not have the title and description of Yoast SEO translated.

No matter what language I am browsing, only what is defined in Yoast SEO is displayed. Does it happen there too?

**Comment by Chouby** [comment]
This is a known issue since Yoast 14.0. These options are translated thanks to the multilingual integration included in the Yoast code. This happens in the wpml-config.xml file that is included in the plugin here: https://github.com/Yoast/wordpress-seo/blob/14.1/wpml-config.xml#L14-L43

This configuration file allows WPML and Polylang to translate **options**. The issue is that since the version 14.0, Yoast moved these options to a custom table and thus bypass the WordPress filters. So they broke their own integration with the multilingual plugins.

The only solution provided by Yoast at the time is that all Polylang and WPML users use Yoast 13.5 and don't update to 14.x.
See https://wordpress.org/support/topic/problema-with-meta-description-homepage-wpml/
or https://wordpress.org/support/topic/click-here-to-speed-up-button-takes-forever/

**Comment by jdevalk** [comment]
Hi, Joost here, from Yoast :)

While what @Chouby says is technically correct, it looks as though we broke something. We didn't. We made a conscious decision to move our meta data, as this allows us to speed sites up tremendously, and we offered new filters to multilingual plugins to change their integration. We communicated about this from a month before release of 14.0, but unfortunately, Polylang isn't finished with their fix yet. So, you can't update to 14.0 yet, because Polylang isn't ready yet. 

We didn't know Polylang was using the `wpml-config.xml` file, had we known we might have reached out to them earlier, as we _did_ do to WPML. So, in short. Wait until Polylang fixes this, don't expect a fix from us, we've done all we can.

**Comment by fredy31** [comment]
Thanks Joost!

Yeah I assumed somewhere along the line someone had changed a function and it broke how Polylang and Yoast communicate together.

And for those who find this thread, if you know how to deal with PHP, using the hooks worked great for the description. Had some trouble to change the title tho.

See this page for the Yoast Hook http://hookr.io/filters/wpseo_metadesc/

And also, if I could ask something of your team Joost; could those hooks be explained in your doc somewhere? The only places I found it mentionned are on some third party sites, and I guess they dont have everything that could be hooked on.

**Comment by grappler** [comment]
@Chouby This has not yet been fixed yet?

**Comment by nalmeida84** [comment]
Im having similar issue. I cant translate even the main page.

`

	<title>Best of Gran Canaria - Information and advice about tourism, coronavirus, car rental, areas, beaches, the best time to visit the island and much more so that you can plan your trip yourself</title>
	<meta name="description" content="Información y consejos sobre turismo en Gran Canaria: coronavirus, alquiler de coches, zonas, playas, mejor tiempo para visitar la isla y muchos más para que puedas planificar tu viaje por tu cuenta." />
	<meta name="robots" content="index, follow" />
	<meta name="googlebot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
	<meta name="bingbot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
	<link rel="canonical" href="https://www.bestofgrancanaria.com/" />
	<meta property="og:locale" content="en_GB" />
	<meta property="og:locale:alternate" content="de_DE" />
	<meta property="og:locale:alternate" content="es_ES" />
	<meta property="og:type" content="website" />
	<meta property="og:title" content="Best of Gran Canaria - Information and advice about tourism, coronavirus, car rental, areas, beaches, the best time to visit the island and much more so that you can plan your trip yourself" />
	<meta property="og:description" content="Información y consejos sobre turismo en Gran Canaria: coronavirus, alquiler de coches, zonas, playas, mejor tiempo para visitar la isla y muchos más para que puedas planificar tu viaje por tu cuenta." />
	<meta property="og:url" content="https://www.bestofgrancanaria.com/en/" />
	<meta property="og:site_name" content="Best of Gran Canaria" />
	
`
I already translated "description" in metadesc-home-wpseo string. The title it's working but not description translation.

**Comment by GGustavoGuerra** [comment]
@Chouby Any news about this?
