### ISSUE TITLE
Category not updated

### ISSUE THREAD

**Issue by vielhuber** [polylang/polylang#574]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Open up a category and choose foreign language
2. Click save
3. Error message "Category not updated"

## Expected behavior and actual behavior

Normally save category.

## Workaround

- Change slug to something different
- Hit save (not it works)
- Change slug back again
- Hit save (works again)

**Comment by Chrystll** [comment]
I don't reproduce your issue on my side. Could you please describe your issue step by step with screenshots so that I understand exactly what is happening? To well understand the context of your screenshots please:

- don't remove anything such as the left wp-admin menu as well the tool bar,

- and set the wp-admin language on English.
