### ISSUE TITLE
How to get original string from translation

### ISSUE THREAD

**Issue by galengidman** [polylang/polylang#61]
How would I go about getting the original string from the translated version of the string? For example:

Original String (en_US): `Full Name`
Translation (de_DE): `Vor- und Nachname`

I'd like to have some kind of a function that looked something like this:

`prefix_get_original_pll_translation( 'Vor- und Nachname', 'en_US' )` which returned `Full Name`. I was hoping `pll_translate_string()` would be able to handle this, but it only seems to work when translating the original language to an alternate, but not an alternate back to the original.

Is this possible?

**Comment by Chouby** [comment]
Under the hood, the strings translations system is using the WordPress translation system with po/mo files. The only difference is that strings are stored in DB instead of the .mo file. This translation works in only one direction.

If you create your own MO child class, you should be able to [add entries in the other direction](https://github.com/polylang/polylang/blob/2.0.9/include/mo.php#L66) and then obtain a function to translate the strings in the other direction.
