### ISSUE TITLE
Images stored as WP attachment ID not being displayed

### ISSUE THREAD

**Issue by Niksmik** [polylang/polylang#620]
Hello,

I'd like to report a bug where on my secondary language pages, the images stored as WP attachment ID are not being shown/displayed anymore. I think this happened after the latest update. The images stored as image URL are displaying OK. Also, the main language pages display all the images correctly.
Thank you for any help/ideas.

Veronika

**Comment by Chrystll** [comment]
As far I understand it seems that the issue is that you were exploiting a bug that we fixed in Polylang 2.8. Probably that you have activated the media translation but you did not translated the media present in the Media Library.
You have 2 solutions:

- either you disable the media translation if you never translate the title, caption, alternative text,

- or you must translate your media and not use media from one language in a post in another language.

**Comment by Niksmik** [comment]
Thank you for getting back to me, I did as you suggested in the comment and turned the media translation off, worked perfectly, thanks.
