### ISSUE TITLE
rest api translations slug

### ISSUE THREAD

**Issue by vana-dev** [polylang/polylang#704]
Currently in post/page rest api we have lists of ids to translated elements, how to change it to list of slugs? It will be much more use useful in pages with urls based on slugs, not ids.

**Comment by Chouby** [comment]
You can't change the list of ids to a list of a slugs. If you need the post slug, then you need to make an additional request. That's the same for example as for categories. When you retrieve a post yu get only the category ids. If you need more, then you need to make an additional request.

For support questions on Polylang Pro, please use our helpdesk rather than GitHub. You'll get fastr answers.
