### ISSUE TITLE
One page / post in all language

### ISSUE THREAD

**Issue by beherit** [polylang/polylang#75]
Could You add new functionality which will add ability to set for page / post not only one language but all language available on page? For now I use on my one website another multilanguage plugin where I can set such page hierarchy:

http://domain.tld/en/wordpress/plugins/something
http://domain.tld/pl/wordpress/wtyczki/something

Unfortunately I can't set this same with Polylang because for page named "wordpress" I can set only one language.

**Comment by Chouby** [comment]
Hi,

I worked on the topic during the past months. My conclusion is that it is better to duplicate the page in all languages rather than having a page with several languages. It allows to add nice features such as automatic gallery translations: Imagine that you create a gallery and the only thing you need to translate are the media titles. You add your media and translate the title in the media interface. You create one page with the gallery and then you automatically generate the page translations.

The current version of Polylang Pro allows this duplication. The next version 2.1 will allow to synchronize two post translations which will give you an equivalent of the unique post for all languages.

**Comment by MatthiasLohr** [comment]
That does not really help me, i would like to see that feature, too.

My blog is not intended to provide much content in different languages, only some special pages. For that (e.g. linking via alternate links etc.) Polylang does a really good job. My biggest problem is, that i can't direcly link to "last posts written in lang xx" when i'm currently on lang yy... A widget option, where i could select the target language (at least for the recent posts, but categories would be great also).

Could you maybe reconsider that for allowing such an option - at least for the recent posts widget?

Thanks in advance
Matthias

**Comment by edirpedro** [comment]
@Chouby 

I'm building my first multilingual website and I'm running at the same boring situation where I can't use the same page for all languages. In my case, it's an application and not a website, the pages won't have any content, they just run a template selected for that page, strings are translated using PO files and content came from other post types or forms. 

I don't know how hard is to implement this, but the language selector to attach it for a page could have an option "All languages" to sign when the page can be used for any language slug (/pt/profile, /en/profile, /es/profile, ...) and instead of redirect you just open that page and let that page care about the translations.

This feature would make it easier to build apps with WordPress because I would not need to translate the page slugs, I could use a single page. I had to build menus manually too, but when you have many languages, you got crazy working this way, duplicating pages and menus. I duplicated pages and made menus my own to avoid more complexity.

**Comment by Rik44444** [comment]
Hi, a question to ask: is this possible now in Polylang Pro? To assign multiple languages to 1 page?

**Comment by Swoopy** [comment]
Hi @Chouby! I have a website where I use custom post type for work references. in these reference posts I have galleries and different types of data. Most of the text are in the templates based on different languages. I use the custom post only to fill the template dynamic fields. As I have more than 100 posts and 3 languages I need to sync 300 post items. On top of that, I'm using menu_order field to order my post list and naming the items, which is nearly impossible with syncing.
It would be much easier if I could assign these posts to all languages to have URLs like:
- "domain.com/custom-post-type/post-1",
- "domain.com/en/custom-post-type/post-1",
- "domain.com/de/custom-post-type/post-1",
without having 3 identical "post-1" for every language. Is that possible somehow?
