### ISSUE TITLE
custom static front page not work

### ISSUE THREAD

**Issue by Shaun-Yao** [polylang/polylang#80]
I have deployed the project on our centos server with xampp,  static front page not work now, but it work when i stop the polylang and also work on my win7 pc with wamp.

**Comment by Thepriestdude** [comment]
I'm running my server via localhost and are encountering the same problem.

When polylang is disabled, the front-page is loaded just fine, but when polylang is activated I get redirected to the post default page. 

I have two different pages set up for my front page, Home and Home_en

**Comment by Chouby** [comment]
@yaoshenghong I need more details to reproduce a bug. Check the differences between your centos and your win7 install at settings level. I don't believe that the issue is coming from the OS.

@Thepriestdude Check that your Home and Home_en are translations of each other. Otherwise you get the result you are describing.

**Comment by jacquesletesson** [comment]
@Chouby I experience the same problem ! 

The page has been translated but the static front-page doesn't show up.

Server is NGINX on Ubuntu 16.04. 

If I disable Polylang, the static front-page shows up.

**Comment by Chouby** [comment]
@jacquesletesson Dis you translate your static front page in all languages? Does it work with Twenty Sixteen?

**Comment by sergiobd** [comment]
The same happens to me. I have not been able to solve this problem.
