### ISSUE TITLE
x-default tags missing

### ISSUE THREAD

**Issue by arcticguesthouse** [polylang/polylang#826]
## Prerequisites

- [ ] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Setup Polylang and create languages
2. Check the page source code
3. Notice that there are no x-default tags

## Expected behavior and actual behavior

The hreflang tags are correctly created but the x-default tag is missing.

I am using two language website (Finnish and English) out of which the Finnish language of course is mainly meant for Finnish customers. The English (currently set as EN_UK) on the other hand should be directed worldwide audiences. I think in these kind of scenarios the x-default tag would be needed as we are not targeting just user with UK English queries but globally.

**Comment by arcticguesthouse** [comment]
https://developers.google.com/search/blog/2013/04/x-default-hreflang-for-international-pages

> The new x-default hreflang attribute value signals to our algorithms that this page doesn't target any specific language or locale and is the default page when no other page is better suited. For example, it would be the page our algorithms try to show French-speaking searchers worldwide or English-speaking searchers on google.ca.

**Comment by Chouby** [comment]
Polylang outputs x-default hreflang attribute when it is necessary, i.e. for the site root page when it is auto-redirected (this occurs when you decided not to hide the language code in the url for the default language in Polylang settings). See https://github.com/polylang/polylang/blob/3.0.3/frontend/frontend-filters-links.php#L237-L239

In the other cases, your pages have all a defined language with its associated hreflang attribute. Google optionnally allows you to add the x-default hreflang attribute for the case you mentioned, but this is not mandatory. The issue is that we have no way to know which language you would like to associate to the x-default. This could be the default language, but this could be a different one. For example, in your case, you may have Finnish as default language and want to output x-default attribute for English. We could also imagine cases where this x-default attribute is not desired.

That's why we don't output the x-default attribute where it's optional. In such case, you can use our filter to add it yourself: https://github.com/polylang/polylang/blob/3.0.3/frontend/frontend-filters-links.php#L241-L248

**Comment by arcticguesthouse** [comment]
Thanks Chouby. Makes sense. Could you please give me an easy and short guide on which part of the code I should paste and where?

**Comment by alex02** [comment]
@arcticguesthouse You can add this snippet to Code Snippets or your theme's functions.php file in order to add x-default hreflang:

```
function polylang_add_xdefault( $hreflangs ) {
	$default = array(
		'x-default' => reset( $hreflangs ) // Fetch the first language URL in the list as x-default
	);
	
	return $hreflangs = $default + $hreflangs;
}

add_filter( 'pll_rel_hreflang_attributes', 'polylang_add_xdefault', 10, 1 );
```

**Comment by BlackStar1991** [comment]
[alex02](https://github.com/alex02) Hi, can you axplaine how to add x-default on a last position in this list ?

**Comment by SeoDeveloper01** [comment]
I refactored the code above, it does exactly the same task, but it runs a little faster and uses less memory.

```
add_filter('pll_rel_hreflang_attributes', function ($hreflangs) {
    $hreflangs['x-default'] = $hreflangs[array_key_first($hreflangs)];
    return $hreflangs;
}, 10, 1);
```

**Comment by cihankaracom** [comment]
"x-default" must be used as default language, so there is no need to add alternate hreflang tag for it. you can check sitemap structure that [Google gives as an example](https://developers.google.com/search/docs/specialty/international/localized-versions). "x-default" should be last element. So I refactored the code accordingly:

`function polylang_add_xdefault( $hreflangs ) {
    $default = array('x-default' => array_shift($hreflangs));
    return $hreflangs + $default;
}

add_filter( 'pll_rel_hreflang_attributes', 'polylang_add_xdefault', 10);`

_Note: add this into functions.php in your theme_
