### ISSUE TITLE
Site gives Fatal error after updating to v2.1

### ISSUE THREAD

**Issue by webkesbuilder** [polylang/polylang#87]
WordPress version is 4.7.1

Hi there, after updating to version 2.1 our websites break down with a fatal error.

```
Fatal error: Method Timber\FunctionWrapper::__toString() must not throw an exception, caught Error: Cannot use object of type Closure as array in /home/pathtowebsite/public_html/wp-content/cache/gantry5/g5_hydrogen/twig/09/0929f7a467bbd193fcfb556012a165e38a82c222345b0e71c6eb60d30d24e155ee.php on line 0
```

Reverting back to version 2.0.12 resolves the issue.

Not sure if this is a bug or some sort of compatibility issue?

**Comment by Chouby** [comment]
It may be a compatibility issue. As the fatal error dos not occur in Polylang, I cannot help much. We see Gantry in the error message. Does the fatal error disappear if you deactivate it? If yes, please report the issue to them.

NB: Your message refers to closures. There are not PHP closures in Polylang because they are not compatible with PHP 5.2 and I try to maintain the compatibility with this old PHP version because WP does.
