### ISSUE TITLE
Translated pages are not saved when saving a fixed page.

### ISSUE THREAD

**Issue by KMKNNKA1** [polylang/polylang#906]
Version: Free version (3.1)

- When I tried to post from a fixed page, the translated page(#tr_lang_XXX,post_tr_lang[XXXX]) was not saved.
- When I reverted to version 3.0.6, it was cured.
- PHP Warning:Invalid argument supplied for foreach() in /xxx/plugins/polylang/include/translated-object.php on line 260, referer: https://hoge.com/wp-admin/post.php?post=0000&action=edit

**Comment by Chouby** [comment]
Your issue looks like the one reported in https://wordpress.org/support/topic/error-when-generating-other-language-version-since-update-version/ caused by a 3rd party plugin. 

The next time you believe that you have found a bug, please follow carefully the steps in the issue form (for example, testing without any other plugin activated).
