### ISSUE TITLE
Redundant loading of WooCommerce mofile

### ISSUE THREAD

**Issue by jayhall69** [polylang/polylang#99]
wordpress 4.7.1
PLL 2.1.1
WC 2.6.14

This issue is not theme dependant. All other plugins disabled.

Polylang and woocommerce leads to repeated loading of woocommerce-de_DE.mo
in the frontend *only* when logged in as admin.

Function load_textdomain_mofile() in OLT Manager class is being called hundreds of times with domain ‘woocommerce’.

**Comment by Chouby** [comment]
I don't reproduce the issue.

I checked this, logged in as admin:
WP 4.7.2
PLL 2.1.1
WC 2.6.14

Language set from the directory name: PLL_OLT_Manager::load_textdomain_mofile() never called
Language set from the content: PLL_OLT_Manager::load_textdomain_mofile() called 3 times with the domain woocommerce.

The purpose of this function is to prevent loading the translation file before the language is definitely set by Polylang. So the goal is to improve the performance as loading a translation file is very expensive. It used to be called only once per domain, but since WP 4.7 and the apparition of the function `_load_textdomain_just_in_time` which allows a plugin to use l10n function without prior call to `load_plugin_textdomain`, it may be called several times per domain.

**Comment by jayhall69** [comment]
Thanks, i looked further into this. The textdomain 'woocommerce' has been loaded about 240 times by the private function in `i10n.php` you mentioned. 

I could prevent this by 

`$GLOBALS['l10n_unloaded']['woocommerce'] = true;`

More information about my setup
- Language is set by content.
- 2 languages, 32 pages, 17 wc products (only in default language), 27 product categories (only in default language), 59 registered strings.

**Comment by Chouby** [comment]
`_load_textdomain_just_in_time()` calls `load_textdomain()` which loads the translation file. The file can be changed by the filter [load_textdomain_mofile](https://github.com/WordPress/WordPress/blob/4.7.2/wp-includes/l10n.php#L581). This is what's done [in the class PLL_OLT_Manager](https://github.com/polylang/polylang/blob/2.1.1/include/olt-manager.php#L164-L167). As you can see, as long as the Polylang language is not set, the translation file is filtered to an empty string, thus preventing the file to be loaded. If the file is loaded anyway, then that may come from a conflict. Dis you try with a default theme such as Twenty Sixteen, Polylang and WooCommerce and no other plugin activated?
