### ISSUE TITLE
 Fatal error: Allowed memory size exhausted translate-option.php on line 112

### ISSUE THREAD

**Issue by UnitedThemes** [polylang/polylang#996]
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [ ] This bug happens with only Polylang plugin active
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently

## Steps to reproduce the issue

1. We are looping over a very large array of theme options in our theme and with every match of a specific optiopn type such as a text filed we call icl_t( 'Theme Options', $id, $cvalue )to register the option and make it translateable.

However this causes a fatal error with out of memory (strangely not on every hosting plattform). 

Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 81920 bytes) in /public_html/wp-content/plugins/polylang/include/translate-option.php on line 112

When tracking the code I found this:

`foreach ( $values as $n => &$value ) {
						// The first case could be handled by the next one, but we avoid calls to preg_match here.
						if ( '*' === $name || ( false !== strpos( $name, '*' ) && preg_match( $pattern, $n ) ) ) {
							$value = $this->translate_string_recursive( $value, $child );
						}
					}`

What I don't understand with the code is:

 **&$value**

Doesnt that keep a reference of the variable -but at the same time the variable is overwritten?

Could that be the issue?

**Comment by manooweb** [comment]
> Doesnt that keep a reference of the variable -but at the same time the variable is overwritten?

I don't think so. A reference on a variable make it only one place in memory in fact and so consume less memory.

I think the issue comes rather from `We are looping over a very large array of theme options` and as the complexity of these options structures.
Indeed, as you can see, the part of the code you pointed is recursive and if the first array is large and each option is also large array, it can explain why we need a lot of memory to translate all of these options in one time.

Could provide us a concrete example of what `large` array mean?

Thanks
